/*
 * PlugInTab.java
 *
 * Created on November 15, 2008, 9:16 PM
 */

package edu.stanford.atom.sti.client.gui;

import javax.swing.JToolBar;
import javax.swing.JPanel;

/**
 *
 * @author  Owner
 */
public class PlugInTab extends JToolBar {
    
    private String tabName = null;
    private int tabIndex = -1;  //uninitialized value
    private JPanel panel;

    /** Creates new PlugInTab
     * @param TabName The name of the tab in the tabbed pane.  If not null, this overrides
     * the name given in JTabbedPane.addTab(...).
     * @param ToolBarName The name of the toolbar when detached from the tabbed pane.
     */
    public PlugInTab(String TabName, String ToolBarName) {
        setTabName(TabName);
        setToolBarName(ToolBarName);
        initComponents();
    }
    public PlugInTab(String name) {
        this(name, name);
    }
    public PlugInTab() {
        this(null, null);
    }
    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        panel.setEnabled(enabled);
    }
    public void setTabName(String TabName) {
        tabName = TabName;
    }
    public String getTabName() {
        return tabName;
    }
    public void setToolBarName(String ToolBarName) {
        setName(ToolBarName);
    }
    public String getToolBarName() {
        return getName();
    }
    public int getTabIndex() {
        return tabIndex;
    }
    public void setTabIndex(int index) {
        tabIndex = index;
    }
    public JPanel getContentPanel() {
        return panel;
    }
    public void setContentPanel(JPanel contentPanel) {
        panel = contentPanel;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
