/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OscilloscopePanel.java
 *
 * Created on Nov 8, 2010, 6:16:08 PM
 */

package edu.stanford.atom.sti.client.gui.oscilloscope;

import edu.stanford.atom.sti.corba.Types.TValMixed;
import edu.stanford.atom.sti.client.comm.bl.device.*;

/**
 *
 * @author Susannah Dickerson
 */
public class OscilloscopePanel extends javax.swing.JPanel {

    public Oscilloscope oscilloscope;
    
    /** Creates new form OscilloscopePanel */
    public OscilloscopePanel() {
        initComponents();

        oscilloscope = new Oscilloscope();
        scopePane.add(oscilloscope.chart);
        scopePane.setSize(150,200);
        scopePane.setViewportView(oscilloscope.chart);
        scopePane.setVisible(true);
    }
           


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        scopePane = new javax.swing.JScrollPane();
        controlsPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        startStopButton = new javax.swing.JToggleButton();
        loadTracesButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 415));

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        scopePane.setPreferredSize(new java.awt.Dimension(300, 300));
        jSplitPane1.setLeftComponent(scopePane);

        controlsPane.setPreferredSize(new java.awt.Dimension(102, 300));

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 300));

        startStopButton.setText("Start/Stop");
        startStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopButtonActionPerformed(evt);
            }
        });

        loadTracesButton.setText("Load Traces");
        loadTracesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTracesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadTracesButton)
                    .addComponent(startStopButton))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(startStopButton)
                .addGap(31, 31, 31)
                .addComponent(loadTracesButton)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        controlsPane.setViewportView(jPanel1);

        jSplitPane1.setRightComponent(controlsPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopButtonActionPerformed
        // TODO add your handling code here:
        
        if (startStopButton.getModel().isSelected())
        {
            oscilloscope.start();
        } else
        {
            oscilloscope.stop();
        }

    }//GEN-LAST:event_startStopButtonActionPerformed

    private void loadTracesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTracesButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_loadTracesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane controlsPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loadTracesButton;
    private javax.swing.JScrollPane scopePane;
    private javax.swing.JToggleButton startStopButton;
    // End of variables declaration//GEN-END:variables
    
}
