/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DocumentationTab.java
 *
 * Created on Dec 17, 2009, 5:05:45 PM
 */

package edu.stanford.atom.sti.client.gui.RunTab;

import edu.stanford.atom.sti.corba.Types.TExpSequenceInfo;

/**
 *
 * @author EP
 */
public class DocumentationTab extends javax.swing.JPanel {

    private TExpSequenceInfo experimentSeqInfo = new TExpSequenceInfo();

    /** Creates new form DocumentationTab */
    public DocumentationTab() {
        initComponents();
    }

    public TExpSequenceInfo getTExpSequenceInfo() {
        experimentSeqInfo.sequenceDescription = sequenceDescription.getText();
        return experimentSeqInfo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sequenceDescription = new javax.swing.JTextArea();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sequence Description"));

        sequenceDescription.setColumns(20);
        sequenceDescription.setRows(5);
        jScrollPane1.setViewportView(sequenceDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea sequenceDescription;
    // End of variables declaration//GEN-END:variables

}
