/*
 * runTabTest.java
 *
 * Created on November 12, 2008, 12:11 PM
 */

package edu.stanford.atom.sti.client.gui.RunTab;

import org.omg.CORBA.*;
import edu.stanford.atom.sti.client.comm.corba.*;
import javax.swing.*;

/**
 *
 * @author  Owner
 */
public class runTabTest extends javax.swing.JFrame {
    
    /** Creates new form runTabTest */
    public runTabTest() {
        getCorbaRefs("localhost", "2809");
        
        initComponents();        
    }
    
    private String ipAddress;
    private String portNumber;
    private ORB orb;
    
    private ExpSequence expSequence;
    private Parser parser;
    
        
    public void getCorbaRefs(String IPAddress, String PortNumber) {

        ipAddress = IPAddress;
        portNumber = PortNumber;

        try {
            String[] extendedArgs = {"-ORBInitialPort", portNumber, "-ORBInitialHost", ipAddress};
            // create and initialize the ORB
            orb = ORB.init(extendedArgs, null);

            org.omg.CORBA.Object expSeqObj = orb.string_to_object(
                    "corbaname::" + ipAddress + ":" + portNumber +
                    "#STI/Client/ExpSequence.Object");
            
            expSequence = ExpSequenceHelper.narrow(expSeqObj);
            
            org.omg.CORBA.Object parserObj = orb.string_to_object(
                    "corbaname::" + ipAddress + ":" + portNumber +
                    "#STI/Client/Parser.Object");
            
            parser = ParserHelper.narrow(parserObj);

        } catch (Exception e) {
            System.out.println("ERROR : " + e);
            e.printStackTrace(System.out);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        runTab1 = new edu.stanford.atom.sti.client.gui.RunTab.RunTab(expSequence, parser);
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runTab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(runTab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception unused) {
            unused.printStackTrace(); // Ignore exception because we can't do anything.  Will use default.
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new runTabTest().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JToolBar jToolBar1;
    private edu.stanford.atom.sti.client.gui.RunTab.RunTab runTab1;
    // End of variables declaration//GEN-END:variables
    
}
