Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TValue Class Reference
edu::stanford::atom::sti::client::comm::corba::TValue
edu::stanford::atom::sti::client::comm::corba::TValue Class Reference
Public Member Functions
int value ()
Static Public Member Functions
static
edu.stanford.atom.sti.client.comm.corba.TValue from_int (int value)
Static Public Attributes
static final int _ValueNumber = 0
static final
edu.stanford.atom.sti.client.comm.corba.TValue ValueNumber = new edu.stanford.atom.sti.client.comm.corba.TValue(_ValueNumber)
static final int _ValueString = 1
static final
edu.stanford.atom.sti.client.comm.corba.TValue ValueString = new edu.stanford.atom.sti.client.comm.corba.TValue(_ValueString)
static final int _ValueDDSTriplet = 2
static final
edu.stanford.atom.sti.client.comm.corba.TValue ValueDDSTriplet = new edu.stanford.atom.sti.client.comm.corba.TValue(_ValueDDSTriplet)
Protected Member Functions
TValue (int value)
Private Attributes
int __value
Static Private Attributes
static int __size = 3
static
edu.stanford.atom.sti.client.comm.corba.TValue[] __array = new edu.stanford.atom.sti.client.comm.corba.TValue [__size]
Detailed Description
Timing_Server/TValue.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TValue.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::comm::corba::TValue::TValue (int value) [inline, protected]
Definition at line 37 of file TValue.java.
References __array, and __value.
Referenced by edu::stanford::atom::sti::client::comm::corba::TValMixed::number(), edu::stanford::atom::sti::client::comm::corba::TValueHelper::read(), edu::stanford::atom::sti::client::comm::corba::TValMixed::stringVal(), edu::stanford::atom::sti::client::comm::corba::TValMixed::triplet(), edu::stanford::atom::sti::client::comm::corba::TValMixed::verifynumber(), edu::stanford::atom::sti::client::comm::corba::TValMixed::verifystringVal(), and edu::stanford::atom::sti::client::comm::corba::TValMixed::verifytriplet().
Member Function Documentation
int edu::stanford::atom::sti::client::comm::corba::TValue::value () [inline]
Definition at line 24 of file TValue.java.
References __value.
static edu.stanford.atom.sti.client.comm.corba.TValue edu::stanford::atom::sti::client::comm::corba::TValue::from_int (int value) [inline, static]
Definition at line 29 of file TValue.java.
References __array, and __size.
Member Data Documentation
int edu::stanford::atom::sti::client::comm::corba::TValue::__value [private]
Definition at line 13 of file TValue.java.
Referenced by TValue(), and value().
int edu::stanford::atom::sti::client::comm::corba::TValue::__size = 3 [static, private]
Definition at line 14 of file TValue.java.
Referenced by from_int().
edu.stanford.atom.sti.client.comm.corba.TValue [] edu::stanford::atom::sti::client::comm::corba::TValue::__array = new edu.stanford.atom.sti.client.comm.corba.TValue [__size] [static, private]
Definition at line 15 of file TValue.java.
Referenced by from_int(), and TValue().
final int edu::stanford::atom::sti::client::comm::corba::TValue::_ValueNumber = 0 [static]
Definition at line 17 of file TValue.java.
final edu.stanford.atom.sti.client.comm.corba.TValue edu::stanford::atom::sti::client::comm::corba::TValue::ValueNumber = new edu.stanford.atom.sti.client.comm.corba.TValue(_ValueNumber) [static]
Definition at line 18 of file TValue.java.
final int edu::stanford::atom::sti::client::comm::corba::TValue::_ValueString = 1 [static]
Definition at line 19 of file TValue.java.
final edu.stanford.atom.sti.client.comm.corba.TValue edu::stanford::atom::sti::client::comm::corba::TValue::ValueString = new edu.stanford.atom.sti.client.comm.corba.TValue(_ValueString) [static]
Definition at line 20 of file TValue.java.
final int edu::stanford::atom::sti::client::comm::corba::TValue::_ValueDDSTriplet = 2 [static]
Definition at line 21 of file TValue.java.
final edu.stanford.atom.sti.client.comm.corba.TValue edu::stanford::atom::sti::client::comm::corba::TValue::ValueDDSTriplet = new edu.stanford.atom.sti.client.comm.corba.TValue(_ValueDDSTriplet) [static]
Definition at line 22 of file TValue.java.
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TValue.java