Stanford Timing Interface: Client: edu::stanford::atom::sti::client::tabbededitor::EditorGUI Class Reference
edu::stanford::atom::sti::client::tabbededitor::EditorGUI
edu::stanford::atom::sti::client::tabbededitor::EditorGUI Class Reference
Public Member Functions
EditorGUI ()
Static Public Member Functions
static void main (String args[])
Package Attributes
TabbedEditor tabbedEditor
Private Member Functions
void initComponents ()
void buttonNewActionPerformed (java.awt.event.ActionEvent evt)
void buttonOpenActionPerformed (java.awt.event.ActionEvent evt)
void jTabbedPane1StateChanged (javax.swing.event.ChangeEvent evt)
void menuFileNewActionPerformed (java.awt.event.ActionEvent evt)
void menuFileOpenActionPerformed (java.awt.event.ActionEvent evt)
void menuFileCloseActionPerformed (java.awt.event.ActionEvent evt)
void menuFileSaveActionPerformed (java.awt.event.ActionEvent evt)
void menuSaveAsActionPerformed (java.awt.event.ActionEvent evt)
void buttonSaveActionPerformed (java.awt.event.ActionEvent evt)
Private Attributes
javax.swing.JButton buttonNew
javax.swing.JButton buttonOpen
javax.swing.JButton buttonSave
javax.swing.JLabel jLabel1
javax.swing.JMenu jMenu2
javax.swing.JMenuBar jMenuBar1
javax.swing.JSeparator jSeparator1
javax.swing.JTabbedPane jTabbedPane1
javax.swing.JMenu menuFile
javax.swing.JMenuItem menuFileClose
javax.swing.JMenuItem menuFileNew
javax.swing.JMenuItem menuFileOpen
javax.swing.JMenuItem menuFileSave
javax.swing.JMenuItem menuSaveAs
Detailed Description
Author:
Owner
Definition at line 19 of file EditorGUI.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::tabbededitor::EditorGUI::EditorGUI () [inline]
Creates new form EditorGUI
Definition at line 24 of file EditorGUI.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::caretPositionLabelLocal, initComponents(), jLabel1, jTabbedPane1, and tabbedEditor.
Referenced by main().
Member Function Documentation
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::initComponents () [inline, private]
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 37 of file EditorGUI.java.
References buttonNew, buttonNewActionPerformed(), buttonOpen, buttonOpenActionPerformed(), buttonSave, buttonSaveActionPerformed(), jLabel1, jMenu2, jMenuBar1, jSeparator1, jTabbedPane1, jTabbedPane1StateChanged(), menuFile, menuFileClose, menuFileCloseActionPerformed(), menuFileNew, menuFileNewActionPerformed(), menuFileOpen, menuFileOpenActionPerformed(), menuFileSave, menuFileSaveActionPerformed(), menuSaveAs, and menuSaveAsActionPerformed().
Referenced by EditorGUI().
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::buttonNewActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 177 of file EditorGUI.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::createNewFile(), and tabbedEditor.
Referenced by initComponents().
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::buttonOpenActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 183 of file EditorGUI.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::openFileInNewTab(), and tabbedEditor.
Referenced by initComponents().
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::jTabbedPane1StateChanged (javax.swing.event.ChangeEvent evt) [inline, private]
Definition at line 188 of file EditorGUI.java.
Referenced by initComponents().
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileNewActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 192 of file EditorGUI.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::createNewFile(), and tabbedEditor.
Referenced by initComponents().
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileOpenActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 197 of file EditorGUI.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::openFileInNewTab(), and tabbedEditor.
Referenced by initComponents().
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileCloseActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 202 of file EditorGUI.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::closeFileInActiveTab(), and tabbedEditor.
Referenced by initComponents().
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileSaveActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 207 of file EditorGUI.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::saveActiveTab(), and tabbedEditor.
Referenced by initComponents().
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuSaveAsActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 212 of file EditorGUI.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::saveAsActiveTab(), and tabbedEditor.
Referenced by initComponents().
void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::buttonSaveActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 217 of file EditorGUI.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::saveActiveTab(), and tabbedEditor.
Referenced by initComponents().
static void edu::stanford::atom::sti::client::tabbededitor::EditorGUI::main (String args[]) [inline, static]
Parameters:
args the command line arguments
Definition at line 225 of file EditorGUI.java.
References EditorGUI().
Member Data Documentation
TabbedEditor edu::stanford::atom::sti::client::tabbededitor::EditorGUI::tabbedEditor [package]
Definition at line 21 of file EditorGUI.java.
Referenced by buttonNewActionPerformed(), buttonOpenActionPerformed(), buttonSaveActionPerformed(), EditorGUI(), menuFileCloseActionPerformed(), menuFileNewActionPerformed(), menuFileOpenActionPerformed(), menuFileSaveActionPerformed(), and menuSaveAsActionPerformed().
javax.swing.JButton edu::stanford::atom::sti::client::tabbededitor::EditorGUI::buttonNew [private]
Definition at line 241 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JButton edu::stanford::atom::sti::client::tabbededitor::EditorGUI::buttonOpen [private]
Definition at line 242 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JButton edu::stanford::atom::sti::client::tabbededitor::EditorGUI::buttonSave [private]
Definition at line 243 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JLabel edu::stanford::atom::sti::client::tabbededitor::EditorGUI::jLabel1 [private]
Definition at line 244 of file EditorGUI.java.
Referenced by EditorGUI(), and initComponents().
javax.swing.JMenu edu::stanford::atom::sti::client::tabbededitor::EditorGUI::jMenu2 [private]
Definition at line 245 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JMenuBar edu::stanford::atom::sti::client::tabbededitor::EditorGUI::jMenuBar1 [private]
Definition at line 246 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JSeparator edu::stanford::atom::sti::client::tabbededitor::EditorGUI::jSeparator1 [private]
Definition at line 247 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JTabbedPane edu::stanford::atom::sti::client::tabbededitor::EditorGUI::jTabbedPane1 [private]
Definition at line 248 of file EditorGUI.java.
Referenced by EditorGUI(), and initComponents().
javax.swing.JMenu edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFile [private]
Definition at line 249 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileClose [private]
Definition at line 250 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileNew [private]
Definition at line 251 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileOpen [private]
Definition at line 252 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileSave [private]
Definition at line 253 of file EditorGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuSaveAs [private]
Definition at line 254 of file EditorGUI.java.
Referenced by initComponents().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/tabbededitor/EditorGUI.java