Stanford Timing Interface: Client: edu::stanford::atom::sti::client::gui::PlotterGUI Class Reference
edu::stanford::atom::sti::client::gui::PlotterGUI
edu::stanford::atom::sti::client::gui::PlotterGUI Class Reference
Public Member Functions
PlotterGUI ()
Static Public Member Functions
static void main (String args[])
Package Attributes
TabbedPlotter tabbedPlotter
Private Member Functions
void initComponents ()
void buttonNewActionPerformed (java.awt.event.ActionEvent evt)
void menuFileNewActionPerformed (java.awt.event.ActionEvent evt)
void menuFileOpenActionPerformed (java.awt.event.ActionEvent evt)
void menuFileCloseActionPerformed (java.awt.event.ActionEvent evt)
void menuFileSaveActionPerformed (java.awt.event.ActionEvent evt)
void menuSaveAsActionPerformed (java.awt.event.ActionEvent evt)
void outputTabbedPaneStateChanged (javax.swing.event.ChangeEvent evt)
void buttonCloseActionPerformed (java.awt.event.ActionEvent evt)
void buttonCurrentActionPerformed (java.awt.event.ActionEvent evt)
Private Attributes
javax.swing.JButton buttonClose
javax.swing.JButton buttonCurrent
javax.swing.JButton buttonNew
javax.swing.JLabel functionInputLabel
javax.swing.JPanel inputPanel
javax.swing.JScrollPane inputScrollPane
javax.swing.JTextArea inputTextArea
javax.swing.JMenu jMenu2
javax.swing.JMenu jMenu3
javax.swing.JMenuBar jMenuBar1
javax.swing.JMenuBar jMenuBar2
javax.swing.JSeparator jSeparator1
javax.swing.JSeparator jSeparator2
javax.swing.JMenu menuFile
javax.swing.JMenu menuFile1
javax.swing.JMenuItem menuFileClose
javax.swing.JMenuItem menuFileClose1
javax.swing.JMenuItem menuFileNew
javax.swing.JMenuItem menuFileNew1
javax.swing.JMenuItem menuFileOpen
javax.swing.JMenuItem menuFileSave
javax.swing.JMenuItem menuFileSave1
javax.swing.JMenuItem menuSaveAs
javax.swing.JMenuItem menuSaveAs1
javax.swing.JTabbedPane outputTabbedPane
Detailed Description
Author:
Owner
Definition at line 19 of file PlotterGUI.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::gui::PlotterGUI::PlotterGUI () [inline]
Creates new form EditorGUI
Definition at line 24 of file PlotterGUI.java.
References initComponents(), inputTextArea, outputTabbedPane, and tabbedPlotter.
Referenced by main().
Member Function Documentation
void edu::stanford::atom::sti::client::gui::PlotterGUI::initComponents () [inline, private]
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 35 of file PlotterGUI.java.
References buttonClose, buttonCloseActionPerformed(), buttonCurrent, buttonCurrentActionPerformed(), buttonNew, buttonNewActionPerformed(), functionInputLabel, inputPanel, inputScrollPane, inputTextArea, jMenu2, jMenu3, jMenuBar1, jMenuBar2, jSeparator1, jSeparator2, menuFile, menuFile1, menuFileClose, menuFileClose1, menuFileCloseActionPerformed(), menuFileNew, menuFileNew1, menuFileNewActionPerformed(), menuFileOpen, menuFileOpenActionPerformed(), menuFileSave, menuFileSave1, menuFileSaveActionPerformed(), menuSaveAs, menuSaveAs1, menuSaveAsActionPerformed(), outputTabbedPane, and outputTabbedPaneStateChanged().
Referenced by PlotterGUI().
void edu::stanford::atom::sti::client::gui::PlotterGUI::buttonNewActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 255 of file PlotterGUI.java.
References edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::createNewTab(), inputTextArea, and tabbedPlotter.
Referenced by initComponents().
void edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileNewActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 261 of file PlotterGUI.java.
References edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::createNewTab(), inputTextArea, and tabbedPlotter.
Referenced by initComponents().
void edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileOpenActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 266 of file PlotterGUI.java.
Referenced by initComponents().
void edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileCloseActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 271 of file PlotterGUI.java.
References edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::closeActiveTab(), and tabbedPlotter.
Referenced by initComponents().
void edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileSaveActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 276 of file PlotterGUI.java.
Referenced by initComponents().
void edu::stanford::atom::sti::client::gui::PlotterGUI::menuSaveAsActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 281 of file PlotterGUI.java.
Referenced by initComponents().
void edu::stanford::atom::sti::client::gui::PlotterGUI::outputTabbedPaneStateChanged (javax.swing.event.ChangeEvent evt) [inline, private]
Definition at line 286 of file PlotterGUI.java.
Referenced by initComponents().
void edu::stanford::atom::sti::client::gui::PlotterGUI::buttonCloseActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 290 of file PlotterGUI.java.
References edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::closeActiveTab(), and tabbedPlotter.
Referenced by initComponents().
void edu::stanford::atom::sti::client::gui::PlotterGUI::buttonCurrentActionPerformed (java.awt.event.ActionEvent evt) [inline, private]
Definition at line 295 of file PlotterGUI.java.
References inputTextArea, tabbedPlotter, and edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::updatePlotterTab().
Referenced by initComponents().
static void edu::stanford::atom::sti::client::gui::PlotterGUI::main (String args[]) [inline, static]
Parameters:
args the command line arguments
Definition at line 304 of file PlotterGUI.java.
References PlotterGUI().
Member Data Documentation
TabbedPlotter edu::stanford::atom::sti::client::gui::PlotterGUI::tabbedPlotter [package]
Definition at line 21 of file PlotterGUI.java.
Referenced by buttonCloseActionPerformed(), buttonCurrentActionPerformed(), buttonNewActionPerformed(), menuFileCloseActionPerformed(), menuFileNewActionPerformed(), and PlotterGUI().
javax.swing.JButton edu::stanford::atom::sti::client::gui::PlotterGUI::buttonClose [private]
Definition at line 322 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JButton edu::stanford::atom::sti::client::gui::PlotterGUI::buttonCurrent [private]
Definition at line 323 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JButton edu::stanford::atom::sti::client::gui::PlotterGUI::buttonNew [private]
Definition at line 324 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JLabel edu::stanford::atom::sti::client::gui::PlotterGUI::functionInputLabel [private]
Definition at line 325 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JPanel edu::stanford::atom::sti::client::gui::PlotterGUI::inputPanel [private]
Definition at line 326 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JScrollPane edu::stanford::atom::sti::client::gui::PlotterGUI::inputScrollPane [private]
Definition at line 327 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JTextArea edu::stanford::atom::sti::client::gui::PlotterGUI::inputTextArea [private]
Definition at line 328 of file PlotterGUI.java.
Referenced by buttonCurrentActionPerformed(), buttonNewActionPerformed(), initComponents(), menuFileNewActionPerformed(), and PlotterGUI().
javax.swing.JMenu edu::stanford::atom::sti::client::gui::PlotterGUI::jMenu2 [private]
Definition at line 329 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenu edu::stanford::atom::sti::client::gui::PlotterGUI::jMenu3 [private]
Definition at line 330 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuBar edu::stanford::atom::sti::client::gui::PlotterGUI::jMenuBar1 [private]
Definition at line 331 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuBar edu::stanford::atom::sti::client::gui::PlotterGUI::jMenuBar2 [private]
Definition at line 332 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JSeparator edu::stanford::atom::sti::client::gui::PlotterGUI::jSeparator1 [private]
Definition at line 333 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JSeparator edu::stanford::atom::sti::client::gui::PlotterGUI::jSeparator2 [private]
Definition at line 334 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenu edu::stanford::atom::sti::client::gui::PlotterGUI::menuFile [private]
Definition at line 335 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenu edu::stanford::atom::sti::client::gui::PlotterGUI::menuFile1 [private]
Definition at line 336 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileClose [private]
Definition at line 337 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileClose1 [private]
Definition at line 338 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileNew [private]
Definition at line 339 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileNew1 [private]
Definition at line 340 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileOpen [private]
Definition at line 341 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileSave [private]
Definition at line 342 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileSave1 [private]
Definition at line 343 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::gui::PlotterGUI::menuSaveAs [private]
Definition at line 344 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JMenuItem edu::stanford::atom::sti::client::gui::PlotterGUI::menuSaveAs1 [private]
Definition at line 345 of file PlotterGUI.java.
Referenced by initComponents().
javax.swing.JTabbedPane edu::stanford::atom::sti::client::gui::PlotterGUI::outputTabbedPane [private]
Definition at line 346 of file PlotterGUI.java.
Referenced by initComponents(), and PlotterGUI().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/gui/PlotterGUI.java