Stanford Timing Interface: Client: edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot Class Reference
edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot
edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot Class Reference
Public Member Functions
TabbedPlot (TabbedPlotter tP, int thisTabIndex, int thisTabCreationIndex)
String getTabTitle ()
int getTabIndex ()
JTextPane getTextPane ()
JScrollPane getScrollPane ()
boolean getModified ()
String getPlotsAsString ()
void setTabIndex (int index)
void setGraphSize (double x, double y)
void setGraphRange (double xMin, double xMax, double yMin, double yMax)
void setGraphRange (double xMin, double xMax, double yMin, double yMax, double xGridSpacing, double yGridSpacing)
void setActivePlot (String inputFunction)
void setTabTitle (String tabName)
void setModifed (boolean Modified)
javax.swing.JScrollPane createTab (String inputFunction)
void createAllPlotsFromString (String inputFunction)
Private Member Functions
void initAttributes ()
Vector< String > getCurrentPlots ()
void singlePlotFromString (Color plotColor, final String expression, final String variable)
double parseStringAsMath (String inputFunction, String independentVariable, double independentVariableValue)
Vector< String > inputToVector (String inputStr)
void initContextMenu (JComponent thisComponent, Vector< JMenuItem > menuItems)
Private Attributes
String tabTitle
javax.swing.JScrollPane currentScrollPane
javax.swing.JTextPane textPaneLocal
JXGraph localGraph
Vector< String > localPlotExpressions
JPopupMenu graphContextMenu
int tabIndex
boolean modified
TabbedPlotter currentPlotter
Color[] defaultColors
Detailed Description
Author:
harv
Definition at line 25 of file TabbedPlot.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::TabbedPlot (TabbedPlotter tP, int thisTabIndex, int thisTabCreationIndex) [inline]
Parameters:
tP
thisTabIndex
Definition at line 47 of file TabbedPlot.java.
References currentPlotter, initAttributes(), setTabIndex(), and setTabTitle().
Member Function Documentation
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::initAttributes () [inline, private]
Definition at line 57 of file TabbedPlot.java.
References currentScrollPane, defaultColors, localGraph, localPlotExpressions, and textPaneLocal.
Referenced by TabbedPlot().
String edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::getTabTitle () [inline]
Returns:
Definition at line 84 of file TabbedPlot.java.
References tabTitle.
Referenced by edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::addPlotterTab().
int edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::getTabIndex () [inline]
Returns:
Definition at line 92 of file TabbedPlot.java.
References tabIndex.
JTextPane edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::getTextPane () [inline]
Returns:
Definition at line 100 of file TabbedPlot.java.
References textPaneLocal.
JScrollPane edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::getScrollPane () [inline]
Returns this document's scroll pane
Returns:
Definition at line 108 of file TabbedPlot.java.
References currentScrollPane.
boolean edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::getModified () [inline]
Returns:
Definition at line 116 of file TabbedPlot.java.
References modified.
Vector<String> edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::getCurrentPlots () [inline, private]
Returns:
Accessor method for the currentGraph variable.
currentGraph
See also:
JXGraph
Definition at line 134 of file TabbedPlot.java.
References localPlotExpressions.
Referenced by getPlotsAsString().
String edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::getPlotsAsString () [inline]
Returns a Vector<String> from a given String input delimited by semicolons. Intended to form the first, most basic level of parsing from the text box to the math expression.
Parameters:
inputStr An input string of functions delimited by semicolon followed by space
Returns:
A Vector<String>
See also:
Vector
Definition at line 148 of file TabbedPlot.java.
References getCurrentPlots().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::setTabIndex (int index) [inline]
Parameters:
index
Definition at line 173 of file TabbedPlot.java.
References tabIndex.
Referenced by TabbedPlot().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::setGraphSize (double x, double y) [inline]
Seems like the JXGraph() can't be resized...
Parameters:
x
y
Definition at line 182 of file TabbedPlot.java.
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::setGraphRange (double xMin, double xMax, double yMin, double yMax) [inline]
Method to allow the range of the current plot to be changed. This resets the major grid lines to sensical values.
Parameters:
xMin New minimum value for X in the graph
xMax New maximum value for X in the graph
yMin New minimum value for Y in the graph
yMax New maximum value for Y in the graph
See also:
setGraphRange(double xMin, double xMax, double yMin, double yMax, double xGridSpacing, double yGridSpacing)
Definition at line 196 of file TabbedPlot.java.
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::setGraphRange (double xMin, double xMax, double yMin, double yMax, double xGridSpacing, double yGridSpacing) [inline]
Method to allow the range of the current plot to be changed. Also resets the major grid lines to sensical values.
Parameters:
xMin
xMax
yMin
yMax
xGridSpacing
yGridSpacing
Definition at line 223 of file TabbedPlot.java.
References localGraph.
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::setActivePlot (String inputFunction) [inline]
Parameters:
inputFunction
Definition at line 243 of file TabbedPlot.java.
References createAllPlotsFromString(), localGraph, and localPlotExpressions.
Referenced by edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::updatePlotterTab().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::setTabTitle (String tabName) [inline]
Parameters:
tabName
Definition at line 253 of file TabbedPlot.java.
References tabTitle.
Referenced by TabbedPlot().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::setModifed (boolean Modified) [inline]
Parameters:
Modified
Definition at line 263 of file TabbedPlot.java.
References modified.
javax.swing.JScrollPane edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::createTab (String inputFunction) [inline]
Parameters:
inputFunction
Returns:
Definition at line 274 of file TabbedPlot.java.
References createAllPlotsFromString(), currentScrollPane, and localGraph.
Referenced by edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::addPlotterTab().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::createAllPlotsFromString (String inputFunction) [inline]
Parameters:
inputFunction
Definition at line 287 of file TabbedPlot.java.
References defaultColors, inputToVector(), and singlePlotFromString().
Referenced by createTab(), and setActivePlot().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::singlePlotFromString (Color plotColor, final String expression, final String variable) [inline, private]
Parameters:
plotColor
expression
variable
Definition at line 307 of file TabbedPlot.java.
References localGraph, localPlotExpressions, and parseStringAsMath().
Referenced by createAllPlotsFromString().
double edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::parseStringAsMath (String inputFunction, String independentVariable, double independentVariableValue) [inline, private]
Parameters:
inputFunction
independentVariable
independentVariableValue
Returns:
double
See also:
org.nfunk.jep.JEP
Definition at line 327 of file TabbedPlot.java.
Referenced by singlePlotFromString().
Vector<String> edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::inputToVector (String inputStr) [inline, private]
Parameters:
inputStr
Returns:
Definition at line 349 of file TabbedPlot.java.
Referenced by createAllPlotsFromString().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::initContextMenu (JComponent thisComponent, Vector< JMenuItem > menuItems) [inline, private]
Definition at line 359 of file TabbedPlot.java.
References graphContextMenu.
Member Data Documentation
String edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::tabTitle [private]
Definition at line 28 of file TabbedPlot.java.
Referenced by getTabTitle(), and setTabTitle().
javax.swing.JScrollPane edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::currentScrollPane [private]
Definition at line 29 of file TabbedPlot.java.
Referenced by createTab(), getScrollPane(), and initAttributes().
javax.swing.JTextPane edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::textPaneLocal [private]
Definition at line 30 of file TabbedPlot.java.
Referenced by getTextPane(), and initAttributes().
JXGraph edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::localGraph [private]
Definition at line 31 of file TabbedPlot.java.
Referenced by createTab(), initAttributes(), setActivePlot(), setGraphRange(), and singlePlotFromString().
Vector<String> edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::localPlotExpressions [private]
Definition at line 32 of file TabbedPlot.java.
Referenced by getCurrentPlots(), initAttributes(), setActivePlot(), and singlePlotFromString().
JPopupMenu edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::graphContextMenu [private]
Definition at line 33 of file TabbedPlot.java.
Referenced by initContextMenu().
int edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::tabIndex [private]
Definition at line 34 of file TabbedPlot.java.
Referenced by getTabIndex(), and setTabIndex().
boolean edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::modified [private]
Definition at line 35 of file TabbedPlot.java.
Referenced by getModified(), and setModifed().
TabbedPlotter edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::currentPlotter [private]
Definition at line 37 of file TabbedPlot.java.
Referenced by TabbedPlot().
Color [] edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::defaultColors [private]
Definition at line 38 of file TabbedPlot.java.
Referenced by createAllPlotsFromString(), and initAttributes().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/gui/tabbedplotter/TabbedPlot.java