Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TValueHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TValueHelper
edu::stanford::atom::sti::client::comm::corba::TValueHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TValue that)
static
edu.stanford.atom.sti.client.comm.corba.TValue extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TValue read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TValue value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TValue:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/TValueHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TValueHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TValueHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TValue that) [inline, static]
Definition at line 15 of file TValueHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TValue edu::stanford::atom::sti::client::comm::corba::TValueHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TValueHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TValueHelper::type () [inline, static]
Definition at line 29 of file TValueHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TValueHelper::id () [inline, static]
Definition at line 38 of file TValueHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TValue edu::stanford::atom::sti::client::comm::corba::TValueHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 43 of file TValueHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TValue::TValue().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TValueHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TValue value) [inline, static]
Definition at line 48 of file TValueHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TValueHelper::_id = "IDL:Timing_Server/TValue:1.0" [static, private]
Definition at line 13 of file TValueHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TValueHelper::__typeCode = null [static, private]
Definition at line 28 of file TValueHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TValueHelper.java