Stanford Timing Interface: Client: edu::stanford::atom::sti::client::tabbededitor::TabbedEditor Class Reference
edu::stanford::atom::sti::client::tabbededitor::TabbedEditor
edu::stanford::atom::sti::client::tabbededitor::TabbedEditor Class Reference
Public Member Functions
TabbedEditor (javax.swing.JTabbedPane jTabbedPane, javax.swing.JFrame jFrame, javax.swing.JLabel caretPositionLabel)
void registerTabbedPane (javax.swing.JTabbedPane jTabbedPane)
void registerFrame (javax.swing.JFrame jFrame)
void registerCaretPositionLabel (javax.swing.JLabel caretPositionLabel)
void tabIsModified (int tabIndex) throws ArrayIndexOutOfBoundsException
void tabIsNotModified (int tabIndex) throws ArrayIndexOutOfBoundsException
void addEditorTab (TabbedDocument tabbedDocument)
void removeEditorTab ()
void removeEditorTab (int tabIndex) throws ArrayIndexOutOfBoundsException
void closeFileInActiveTab ()
boolean closeFileInTab (int tabIndex) throws ArrayIndexOutOfBoundsException
void openFileInNewTab ()
void openFileInNewTab (File file)
void openFileInActiveTab ()
void openFileInActiveTab (File file)
void openFileInTab (File file, int tabIndex) throws ArrayIndexOutOfBoundsException
int getIndex (File file)
boolean fileIsOpen (File file)
String readFile (File file)
boolean saveActiveTab ()
boolean saveTab (int tabIndex) throws ArrayIndexOutOfBoundsException
boolean saveAsActiveTab ()
boolean saveAsTab (int tabIndex) throws ArrayIndexOutOfBoundsException
void createNewFile ()
int getUntitledDocCount ()
Public Attributes
javax.swing.JLabel caretPositionLabelLocal
Private Types
enum fileError
Private Member Functions
void tabbedPaneStateChanged (javax.swing.event.ChangeEvent evt)
File openFileDialog ()
boolean writeFile (File file, String dataString)
Private Attributes
Vector< TabbedDocument > tabbedDocumentVector = new Vector<TabbedDocument>()
int untitledDocCount = 0
javax.swing.JTabbedPane jTabbedPaneLocal
javax.swing.JFrame jFrameLocal
Detailed Description
Author:
Jason Hogan
Definition at line 16 of file TabbedEditor.java.
Member Enumeration Documentation
enum edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::fileError [private]
Enumerator:
ReadOnly
ReadError
FileIsOpen
NoError
Definition at line 18 of file TabbedEditor.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::TabbedEditor (javax.swing.JTabbedPane jTabbedPane, javax.swing.JFrame jFrame, javax.swing.JLabel caretPositionLabel) [inline]
Definition at line 25 of file TabbedEditor.java.
References registerCaretPositionLabel(), registerFrame(), registerTabbedPane(), tabbedPaneStateChanged(), and untitledDocCount.
Member Function Documentation
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::registerTabbedPane (javax.swing.JTabbedPane jTabbedPane) [inline]
Definition at line 52 of file TabbedEditor.java.
References jTabbedPaneLocal.
Referenced by TabbedEditor().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::registerFrame (javax.swing.JFrame jFrame) [inline]
Definition at line 56 of file TabbedEditor.java.
References jFrameLocal.
Referenced by TabbedEditor().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::registerCaretPositionLabel (javax.swing.JLabel caretPositionLabel) [inline]
Definition at line 60 of file TabbedEditor.java.
References caretPositionLabelLocal.
Referenced by TabbedEditor().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::tabbedPaneStateChanged (javax.swing.event.ChangeEvent evt) [inline, private]
Definition at line 65 of file TabbedEditor.java.
Referenced by TabbedEditor().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::tabIsModified (int tabIndex) throws ArrayIndexOutOfBoundsException [inline]
Definition at line 70 of file TabbedEditor.java.
References jTabbedPaneLocal, and tabbedDocumentVector.
Referenced by edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::documentIsChanged().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::tabIsNotModified (int tabIndex) throws ArrayIndexOutOfBoundsException [inline]
Definition at line 84 of file TabbedEditor.java.
References jTabbedPaneLocal, and tabbedDocumentVector.
Referenced by createNewFile(), openFileInTab(), saveAsTab(), and saveTab().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::addEditorTab (TabbedDocument tabbedDocument) [inline]
Definition at line 95 of file TabbedEditor.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::generateTab(), edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::getTabTitle(), and jTabbedPaneLocal.
Referenced by createNewFile(), and openFileInTab().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::removeEditorTab () [inline]
Definition at line 100 of file TabbedEditor.java.
References jTabbedPaneLocal.
Referenced by closeFileInTab(), and openFileInTab().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::removeEditorTab (int tabIndex) throws ArrayIndexOutOfBoundsException [inline]
Definition at line 104 of file TabbedEditor.java.
References jTabbedPaneLocal, and tabbedDocumentVector.
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::closeFileInActiveTab () [inline]
Definition at line 119 of file TabbedEditor.java.
References closeFileInTab(), and jTabbedPaneLocal.
Referenced by edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileCloseActionPerformed().
boolean edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::closeFileInTab (int tabIndex) throws ArrayIndexOutOfBoundsException [inline]
Generic close file method.
Parameters:
tabIndex The index of the JTabbedPane that contains the document to close
Returns:
true if the document closed successfully, false otherwise.
Exceptions:
java.lang.ArrayIndexOutOfBoundsException
Definition at line 130 of file TabbedEditor.java.
References jFrameLocal, removeEditorTab(), saveTab(), and tabbedDocumentVector.
Referenced by closeFileInActiveTab().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::openFileInNewTab () [inline]
Definition at line 175 of file TabbedEditor.java.
References openFileDialog().
Referenced by edu::stanford::atom::sti::client::tabbededitor::EditorGUI::buttonOpenActionPerformed(), edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileOpenActionPerformed(), and openFileInTab().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::openFileInNewTab (File file) [inline]
Definition at line 179 of file TabbedEditor.java.
References openFileInTab(), and tabbedDocumentVector.
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::openFileInActiveTab () [inline]
Definition at line 183 of file TabbedEditor.java.
References openFileDialog().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::openFileInActiveTab (File file) [inline]
Definition at line 187 of file TabbedEditor.java.
References jTabbedPaneLocal, and openFileInTab().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::openFileInTab (File file, int tabIndex) throws ArrayIndexOutOfBoundsException [inline]
Generic open file method. If tabIndex is equal to the current number of open tabs (the current size() of the Vector of TabbedDoccuments) then a new tab is created and a new TabbedDoccument element is added to the Vector.
Parameters:
file The File to open
tabIndex The index in the JTabbedPane for the opened file
Exceptions:
java.lang.ArrayIndexOutOfBoundsException Throws an exception if tabIndex is less than zero or if tabIndex is greater than the size of the Vector of TabbedDocuments
Definition at line 201 of file TabbedEditor.java.
References addEditorTab(), FileIsOpen, fileIsOpen(), getIndex(), jFrameLocal, jTabbedPaneLocal, NoError, openFileInNewTab(), ReadError, readFile(), ReadOnly, removeEditorTab(), tabbedDocumentVector, and tabIsNotModified().
Referenced by openFileInActiveTab(), and openFileInNewTab().
File edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::openFileDialog () [inline, private]
Definition at line 336 of file TabbedEditor.java.
References jFrameLocal.
Referenced by openFileInActiveTab(), and openFileInNewTab().
int edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::getIndex (File file) [inline]
Finds the tab index in the JTabbedPane of a particular File currently open in the TabbedEditor.
Parameters:
file The File of interest
Returns:
The index of the tab in the JTabbedPane for this File.
Definition at line 358 of file TabbedEditor.java.
References tabbedDocumentVector.
Referenced by openFileInTab().
boolean edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::fileIsOpen (File file) [inline]
Checks to see if a particular File is already open in the TabbedEditor
Parameters:
file The particular File to check the status of.
Returns:
true if the the File is already open.
false if the File is not open or if the File is null
Definition at line 379 of file TabbedEditor.java.
References tabbedDocumentVector.
Referenced by openFileInTab().
String edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::readFile (File file) [inline]
Definition at line 390 of file TabbedEditor.java.
Referenced by openFileInTab().
boolean edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::saveActiveTab () [inline]
Definition at line 414 of file TabbedEditor.java.
References jTabbedPaneLocal, and saveTab().
Referenced by edu::stanford::atom::sti::client::tabbededitor::EditorGUI::buttonSaveActionPerformed(), and edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileSaveActionPerformed().
boolean edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::saveTab (int tabIndex) throws ArrayIndexOutOfBoundsException [inline]
Generic save method. Calls saveAs(tabIndex) if the document has a null File or is marked as read only.
Parameters:
tabIndex The index of the JTabbedPane that contains the document to save
Returns:
true if the document is sucessfully saved, false otherwise.
Exceptions:
java.lang.ArrayIndexOutOfBoundsException
Definition at line 425 of file TabbedEditor.java.
References jFrameLocal, saveAsTab(), tabbedDocumentVector, tabIsNotModified(), and writeFile().
Referenced by closeFileInTab(), and saveActiveTab().
boolean edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::saveAsActiveTab () [inline]
Definition at line 472 of file TabbedEditor.java.
References jTabbedPaneLocal, and saveAsTab().
Referenced by edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuSaveAsActionPerformed().
boolean edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::saveAsTab (int tabIndex) throws ArrayIndexOutOfBoundsException [inline]
Generic SaveAs method. Prompts for a file name and presents an overwrite confirmation dialog if the file already exists.
Parameters:
tabIndex The index of the JTabbedPane that contains the document to be saved.
Returns:
true if the document is successfully saved, false otherwise.
Exceptions:
java.lang.ArrayIndexOutOfBoundsException
Definition at line 484 of file TabbedEditor.java.
References jFrameLocal, jTabbedPaneLocal, tabbedDocumentVector, tabIsNotModified(), and writeFile().
Referenced by saveAsActiveTab(), and saveTab().
boolean edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::writeFile (File file, String dataString) [inline, private]
Definition at line 532 of file TabbedEditor.java.
Referenced by saveAsTab(), and saveTab().
void edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::createNewFile () [inline]
Creates a blank new document in a new tab with title Untitled#, where # is a number starting from 1 that increments each time a new file is made. The File associated with the newly created TabbedDocument is null.
Definition at line 554 of file TabbedEditor.java.
References addEditorTab(), jTabbedPaneLocal, tabbedDocumentVector, tabIsNotModified(), and untitledDocCount.
Referenced by edu::stanford::atom::sti::client::tabbededitor::EditorGUI::buttonNewActionPerformed(), and edu::stanford::atom::sti::client::tabbededitor::EditorGUI::menuFileNewActionPerformed().
int edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::getUntitledDocCount () [inline]
Definition at line 573 of file TabbedEditor.java.
References untitledDocCount.
Referenced by edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::setTabTitle().
Member Data Documentation
Vector<TabbedDocument> edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::tabbedDocumentVector = new Vector<TabbedDocument>() [private]
Definition at line 576 of file TabbedEditor.java.
Referenced by closeFileInTab(), createNewFile(), fileIsOpen(), getIndex(), openFileInNewTab(), openFileInTab(), removeEditorTab(), saveAsTab(), saveTab(), tabIsModified(), and tabIsNotModified().
int edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::untitledDocCount = 0 [private]
Definition at line 577 of file TabbedEditor.java.
Referenced by createNewFile(), getUntitledDocCount(), and TabbedEditor().
javax.swing.JLabel edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::caretPositionLabelLocal
Definition at line 578 of file TabbedEditor.java.
Referenced by edu::stanford::atom::sti::client::tabbededitor::EditorGUI::EditorGUI(), registerCaretPositionLabel(), and edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::TabbedDocument().
javax.swing.JTabbedPane edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::jTabbedPaneLocal [private]
Definition at line 579 of file TabbedEditor.java.
Referenced by addEditorTab(), closeFileInActiveTab(), createNewFile(), openFileInActiveTab(), openFileInTab(), registerTabbedPane(), removeEditorTab(), saveActiveTab(), saveAsActiveTab(), saveAsTab(), tabIsModified(), and tabIsNotModified().
javax.swing.JFrame edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::jFrameLocal [private]
Definition at line 580 of file TabbedEditor.java.
Referenced by closeFileInTab(), openFileDialog(), openFileInTab(), registerFrame(), saveAsTab(), and saveTab().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/tabbededitor/TabbedEditor.java