Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TRowHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TRowHelper
edu::stanford::atom::sti::client::comm::corba::TRowHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TRow that)
static
edu.stanford.atom.sti.client.comm.corba.TRow extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TRow read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TRow value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TRow/TRow:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
static boolean __active = false
Detailed Description
Timing_Server/TRowHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:01 PM PDT
Definition at line 11 of file TRowHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TRowHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TRow that) [inline, static]
Definition at line 15 of file TRowHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TRow edu::stanford::atom::sti::client::comm::corba::TRowHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TRowHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TRowHelper::type () [inline, static]
Definition at line 30 of file TRowHelper.java.
References __active, __typeCode, and _id.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TRowHelper::id () [inline, static]
Definition at line 65 of file TRowHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TRow edu::stanford::atom::sti::client::comm::corba::TRowHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 70 of file TRowHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TRow::TRow().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TRowHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TRow value) [inline, static]
Definition at line 78 of file TRowHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TRowHelper::_id = "IDL:Timing_Server/TRow/TRow:1.0" [static, private]
Definition at line 13 of file TRowHelper.java.
Referenced by id(), and type().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TRowHelper::__typeCode = null [static, private]
Definition at line 28 of file TRowHelper.java.
Referenced by type().
boolean edu::stanford::atom::sti::client::comm::corba::TRowHelper::__active = false [static, private]
Definition at line 29 of file TRowHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TRowHelper.java