Stanford Timing Interface: Client: edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener Class Reference
edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener
edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener Class Reference
Public Member Functions
tabDocumentListener (TabbedEditor tabbedEditor, TabbedDocument tabbedDocument)
void insertUpdate (DocumentEvent e)
void removeUpdate (DocumentEvent e)
void changedUpdate (DocumentEvent e)
Private Member Functions
void documentIsChanged (DocumentEvent e)
void displayEditInfo (DocumentEvent e)
Private Attributes
TabbedEditor tabbedEditorLocal
TabbedDocument tabbedDocumentLocal
Detailed Description
Author:
Owner
Definition at line 17 of file tabDocumentListener.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::tabDocumentListener (TabbedEditor tabbedEditor, TabbedDocument tabbedDocument) [inline]
Definition at line 20 of file tabDocumentListener.java.
References tabbedDocumentLocal, and tabbedEditorLocal.
Member Function Documentation
void edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::insertUpdate (DocumentEvent e) [inline]
Definition at line 26 of file tabDocumentListener.java.
References documentIsChanged().
void edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::removeUpdate (DocumentEvent e) [inline]
Definition at line 30 of file tabDocumentListener.java.
References documentIsChanged().
void edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::changedUpdate (DocumentEvent e) [inline]
Definition at line 34 of file tabDocumentListener.java.
References documentIsChanged().
void edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::documentIsChanged (DocumentEvent e) [inline, private]
Definition at line 38 of file tabDocumentListener.java.
References edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::getTabIndex(), edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::setModifed(), tabbedDocumentLocal, tabbedEditorLocal, and edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::tabIsModified().
Referenced by changedUpdate(), insertUpdate(), and removeUpdate().
void edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::displayEditInfo (DocumentEvent e) [inline, private]
Definition at line 43 of file tabDocumentListener.java.
Member Data Documentation
TabbedEditor edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::tabbedEditorLocal [private]
Definition at line 48 of file tabDocumentListener.java.
Referenced by documentIsChanged(), and tabDocumentListener().
TabbedDocument edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::tabbedDocumentLocal [private]
Definition at line 49 of file tabDocumentListener.java.
Referenced by documentIsChanged(), and tabDocumentListener().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/tabbededitor/tabDocumentListener.java