Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper
edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TOverwritten[] that)
static
edu.stanford.atom.sti.client.comm.corba.TOverwritten[] extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TOverwritten[] read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TOverwritten[] value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TOverwrittenSeq:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/TOverwrittenSeqHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TOverwrittenSeqHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TOverwritten[] that) [inline, static]
Definition at line 15 of file TOverwrittenSeqHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TOverwritten [] edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TOverwrittenSeqHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper::type () [inline, static]
Definition at line 29 of file TOverwrittenSeqHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper::id () [inline, static]
Definition at line 40 of file TOverwrittenSeqHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TOverwritten [] edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 45 of file TOverwrittenSeqHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TOverwritten::TOverwritten().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TOverwritten[] value) [inline, static]
Definition at line 55 of file TOverwrittenSeqHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper::_id = "IDL:Timing_Server/TOverwrittenSeq:1.0" [static, private]
Definition at line 13 of file TOverwrittenSeqHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TOverwrittenSeqHelper::__typeCode = null [static, private]
Definition at line 28 of file TOverwrittenSeqHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TOverwrittenSeqHelper.java