Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TChannelHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TChannelHelper
edu::stanford::atom::sti::client::comm::corba::TChannelHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TChannel that)
static
edu.stanford.atom.sti.client.comm.corba.TChannel extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TChannel read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TChannel value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TChannel/TChannel:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
static boolean __active = false
Detailed Description
Timing_Server/TChannelHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TChannelHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TChannelHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TChannel that) [inline, static]
Definition at line 15 of file TChannelHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TChannel edu::stanford::atom::sti::client::comm::corba::TChannelHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TChannelHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TChannelHelper::type () [inline, static]
Definition at line 30 of file TChannelHelper.java.
References __active, __typeCode, and _id.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TChannelHelper::id () [inline, static]
Definition at line 63 of file TChannelHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TChannel edu::stanford::atom::sti::client::comm::corba::TChannelHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 68 of file TChannelHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TChannel::TChannel().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TChannelHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TChannel value) [inline, static]
Definition at line 76 of file TChannelHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TChannelHelper::_id = "IDL:Timing_Server/TChannel/TChannel:1.0" [static, private]
Definition at line 13 of file TChannelHelper.java.
Referenced by id(), and type().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TChannelHelper::__typeCode = null [static, private]
Definition at line 28 of file TChannelHelper.java.
Referenced by type().
boolean edu::stanford::atom::sti::client::comm::corba::TChannelHelper::__active = false [static, private]
Definition at line 29 of file TChannelHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TChannelHelper.java