Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TVarMixed Class Reference
edu::stanford::atom::sti::client::comm::corba::TVarMixed
edu::stanford::atom::sti::client::comm::corba::TVarMixed Class Reference
Public Member Functions
TVarMixed ()
edu.stanford.atom.sti.client.comm.corba.TType discriminator ()
double number ()
void number (double value)
void number (edu.stanford.atom.sti.client.comm.corba.TType discriminator, double value)
String stringVal ()
void stringVal (String value)
void stringVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator, String value)
short channel ()
void channel (short value)
void channel (edu.stanford.atom.sti.client.comm.corba.TType discriminator, short value)
String objectVal ()
void objectVal (String value)
void objectVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator, String value)
Private Member Functions
void verifynumber (edu.stanford.atom.sti.client.comm.corba.TType discriminator)
void verifystringVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator)
void verifychannel (edu.stanford.atom.sti.client.comm.corba.TType discriminator)
void verifyobjectVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator)
Private Attributes
double ___number
String ___stringVal
short ___channel
String ___objectVal
edu.stanford.atom.sti.client.comm.corba.TType __discriminator
boolean __uninitialized = true
Detailed Description
Timing_Server/TVarMixed.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TVarMixed.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::comm::corba::TVarMixed::TVarMixed () [inline]
Definition at line 20 of file TVarMixed.java.
Referenced by edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper::read().
Member Function Documentation
edu.stanford.atom.sti.client.comm.corba.TType edu::stanford::atom::sti::client::comm::corba::TVarMixed::discriminator () [inline]
Definition at line 24 of file TVarMixed.java.
References __discriminator, and __uninitialized.
Referenced by channel(), number(), objectVal(), stringVal(), verifychannel(), verifynumber(), verifyobjectVal(), and verifystringVal().
double edu::stanford::atom::sti::client::comm::corba::TVarMixed::number () [inline]
Definition at line 31 of file TVarMixed.java.
References ___number, __discriminator, __uninitialized, and verifynumber().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::number (double value) [inline]
Definition at line 39 of file TVarMixed.java.
References ___number, __discriminator, __uninitialized, and edu::stanford::atom::sti::client::comm::corba::TType::TType().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::number (edu.stanford.atom.sti.client.comm.corba.TType discriminator, double value) [inline]
Definition at line 46 of file TVarMixed.java.
References ___number, __discriminator, __uninitialized, discriminator(), and verifynumber().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::verifynumber (edu.stanford.atom.sti.client.comm.corba.TType discriminator) [inline, private]
Definition at line 54 of file TVarMixed.java.
References discriminator(), and edu::stanford::atom::sti::client::comm::corba::TType::TType().
Referenced by number().
String edu::stanford::atom::sti::client::comm::corba::TVarMixed::stringVal () [inline]
Definition at line 60 of file TVarMixed.java.
References ___stringVal, __discriminator, __uninitialized, and verifystringVal().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::stringVal (String value) [inline]
Definition at line 68 of file TVarMixed.java.
References ___stringVal, __discriminator, __uninitialized, and edu::stanford::atom::sti::client::comm::corba::TType::TType().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::stringVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator, String value) [inline]
Definition at line 75 of file TVarMixed.java.
References ___stringVal, __discriminator, __uninitialized, discriminator(), and verifystringVal().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::verifystringVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator) [inline, private]
Definition at line 83 of file TVarMixed.java.
References discriminator(), and edu::stanford::atom::sti::client::comm::corba::TType::TType().
Referenced by stringVal().
short edu::stanford::atom::sti::client::comm::corba::TVarMixed::channel () [inline]
Definition at line 89 of file TVarMixed.java.
References ___channel, __discriminator, __uninitialized, and verifychannel().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::channel (short value) [inline]
Definition at line 97 of file TVarMixed.java.
References ___channel, __discriminator, __uninitialized, and edu::stanford::atom::sti::client::comm::corba::TType::TType().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::channel (edu.stanford.atom.sti.client.comm.corba.TType discriminator, short value) [inline]
Definition at line 104 of file TVarMixed.java.
References ___channel, __discriminator, __uninitialized, discriminator(), and verifychannel().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::verifychannel (edu.stanford.atom.sti.client.comm.corba.TType discriminator) [inline, private]
Definition at line 112 of file TVarMixed.java.
References discriminator(), and edu::stanford::atom::sti::client::comm::corba::TType::TType().
Referenced by channel().
String edu::stanford::atom::sti::client::comm::corba::TVarMixed::objectVal () [inline]
Definition at line 118 of file TVarMixed.java.
References ___objectVal, __discriminator, __uninitialized, and verifyobjectVal().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::objectVal (String value) [inline]
Definition at line 126 of file TVarMixed.java.
References ___objectVal, __discriminator, __uninitialized, and edu::stanford::atom::sti::client::comm::corba::TType::TType().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::objectVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator, String value) [inline]
Definition at line 133 of file TVarMixed.java.
References ___objectVal, __discriminator, __uninitialized, discriminator(), and verifyobjectVal().
void edu::stanford::atom::sti::client::comm::corba::TVarMixed::verifyobjectVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator) [inline, private]
Definition at line 141 of file TVarMixed.java.
References discriminator(), and edu::stanford::atom::sti::client::comm::corba::TType::TType().
Referenced by objectVal().
Member Data Documentation
double edu::stanford::atom::sti::client::comm::corba::TVarMixed::___number [private]
Definition at line 13 of file TVarMixed.java.
Referenced by number().
String edu::stanford::atom::sti::client::comm::corba::TVarMixed::___stringVal [private]
Definition at line 14 of file TVarMixed.java.
Referenced by stringVal().
short edu::stanford::atom::sti::client::comm::corba::TVarMixed::___channel [private]
Definition at line 15 of file TVarMixed.java.
Referenced by channel().
String edu::stanford::atom::sti::client::comm::corba::TVarMixed::___objectVal [private]
Definition at line 16 of file TVarMixed.java.
Referenced by objectVal().
edu.stanford.atom.sti.client.comm.corba.TType edu::stanford::atom::sti::client::comm::corba::TVarMixed::__discriminator [private]
Definition at line 17 of file TVarMixed.java.
Referenced by channel(), discriminator(), number(), objectVal(), and stringVal().
boolean edu::stanford::atom::sti::client::comm::corba::TVarMixed::__uninitialized = true [private]
Definition at line 18 of file TVarMixed.java.
Referenced by channel(), discriminator(), number(), objectVal(), and stringVal().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TVarMixed.java