Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TType Class Reference
edu::stanford::atom::sti::client::comm::corba::TType
edu::stanford::atom::sti::client::comm::corba::TType Class Reference
Public Member Functions
int value ()
Static Public Member Functions
static
edu.stanford.atom.sti.client.comm.corba.TType from_int (int value)
Static Public Attributes
static final int _TypeNumber = 0
static final
edu.stanford.atom.sti.client.comm.corba.TType TypeNumber = new edu.stanford.atom.sti.client.comm.corba.TType(_TypeNumber)
static final int _TypeString = 1
static final
edu.stanford.atom.sti.client.comm.corba.TType TypeString = new edu.stanford.atom.sti.client.comm.corba.TType(_TypeString)
static final int _TypeChannel = 2
static final
edu.stanford.atom.sti.client.comm.corba.TType TypeChannel = new edu.stanford.atom.sti.client.comm.corba.TType(_TypeChannel)
static final int _TypeObject = 3
static final
edu.stanford.atom.sti.client.comm.corba.TType TypeObject = new edu.stanford.atom.sti.client.comm.corba.TType(_TypeObject)
Protected Member Functions
TType (int value)
Private Attributes
int __value
Static Private Attributes
static int __size = 4
static
edu.stanford.atom.sti.client.comm.corba.TType[] __array = new edu.stanford.atom.sti.client.comm.corba.TType [__size]
Detailed Description
Timing_Server/TType.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TType.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::comm::corba::TType::TType (int value) [inline, protected]
Definition at line 39 of file TType.java.
References __array, and __value.
Referenced by edu::stanford::atom::sti::client::comm::corba::TVarMixed::channel(), edu::stanford::atom::sti::client::comm::corba::TVarMixed::number(), edu::stanford::atom::sti::client::comm::corba::TVarMixed::objectVal(), edu::stanford::atom::sti::client::comm::corba::TTypeHelper::read(), edu::stanford::atom::sti::client::comm::corba::TVarMixed::stringVal(), edu::stanford::atom::sti::client::comm::corba::TVarMixed::verifychannel(), edu::stanford::atom::sti::client::comm::corba::TVarMixed::verifynumber(), edu::stanford::atom::sti::client::comm::corba::TVarMixed::verifyobjectVal(), and edu::stanford::atom::sti::client::comm::corba::TVarMixed::verifystringVal().
Member Function Documentation
int edu::stanford::atom::sti::client::comm::corba::TType::value () [inline]
Definition at line 26 of file TType.java.
References __value.
static edu.stanford.atom.sti.client.comm.corba.TType edu::stanford::atom::sti::client::comm::corba::TType::from_int (int value) [inline, static]
Definition at line 31 of file TType.java.
References __array, and __size.
Member Data Documentation
int edu::stanford::atom::sti::client::comm::corba::TType::__value [private]
Definition at line 13 of file TType.java.
Referenced by TType(), and value().
int edu::stanford::atom::sti::client::comm::corba::TType::__size = 4 [static, private]
Definition at line 14 of file TType.java.
Referenced by from_int().
edu.stanford.atom.sti.client.comm.corba.TType [] edu::stanford::atom::sti::client::comm::corba::TType::__array = new edu.stanford.atom.sti.client.comm.corba.TType [__size] [static, private]
Definition at line 15 of file TType.java.
Referenced by from_int(), and TType().
final int edu::stanford::atom::sti::client::comm::corba::TType::_TypeNumber = 0 [static]
Definition at line 17 of file TType.java.
final edu.stanford.atom.sti.client.comm.corba.TType edu::stanford::atom::sti::client::comm::corba::TType::TypeNumber = new edu.stanford.atom.sti.client.comm.corba.TType(_TypeNumber) [static]
Definition at line 18 of file TType.java.
final int edu::stanford::atom::sti::client::comm::corba::TType::_TypeString = 1 [static]
Definition at line 19 of file TType.java.
final edu.stanford.atom.sti.client.comm.corba.TType edu::stanford::atom::sti::client::comm::corba::TType::TypeString = new edu.stanford.atom.sti.client.comm.corba.TType(_TypeString) [static]
Definition at line 20 of file TType.java.
final int edu::stanford::atom::sti::client::comm::corba::TType::_TypeChannel = 2 [static]
Definition at line 21 of file TType.java.
final edu.stanford.atom.sti.client.comm.corba.TType edu::stanford::atom::sti::client::comm::corba::TType::TypeChannel = new edu.stanford.atom.sti.client.comm.corba.TType(_TypeChannel) [static]
Definition at line 22 of file TType.java.
final int edu::stanford::atom::sti::client::comm::corba::TType::_TypeObject = 3 [static]
Definition at line 23 of file TType.java.
final edu.stanford.atom.sti.client.comm.corba.TType edu::stanford::atom::sti::client::comm::corba::TType::TypeObject = new edu.stanford.atom.sti.client.comm.corba.TType(_TypeObject) [static]
Definition at line 24 of file TType.java.
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TType.java