Stanford Timing Interface: Client: edu::stanford::atom::sti::client::tabbededitor::TabbedDocument Class Reference
edu::stanford::atom::sti::client::tabbededitor::TabbedDocument
edu::stanford::atom::sti::client::tabbededitor::TabbedDocument Class Reference
Public Member Functions
TabbedDocument (File file, TabbedEditor tabbedEditor, int TabIndex)
javax.swing.JScrollPane generateTab ()
void setFile (File file)
File getFile ()
void setTabTitle (File file)
String getTabTitle ()
int getTabIndex ()
void setTabIndex (int index)
javax.swing.JTextPane getTextPane ()
javax.swing.JScrollPane getScrollPane ()
void setModifed (boolean Modified)
boolean isModifed ()
String getCaretLabelText ()
Private Attributes
String tabFileName
javax.swing.JScrollPane scrollPaneLocal = new javax.swing.JScrollPane()
javax.swing.JTextPane textPaneLocal = new javax.swing.JTextPane()
File fileLocal
int tabIndex
boolean modified
CaretListenerLabel caretListenerLocal
AbstractDocument abstractDocumentLocal
TabbedEditor tabbedEditorLocal
Detailed Description
Author:
Owner
Definition at line 16 of file TabbedDocument.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::TabbedDocument (File file, TabbedEditor tabbedEditor, int TabIndex) [inline]
Definition at line 19 of file TabbedDocument.java.
References abstractDocumentLocal, caretListenerLocal, edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::caretPositionLabelLocal, fileLocal, setTabIndex(), setTabTitle(), tabbedEditorLocal, and textPaneLocal.
Member Function Documentation
javax.swing.JScrollPane edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::generateTab () [inline]
Definition at line 45 of file TabbedDocument.java.
References caretListenerLocal, scrollPaneLocal, and textPaneLocal.
Referenced by edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::addEditorTab().
void edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::setFile (File file) [inline]
Definition at line 52 of file TabbedDocument.java.
References fileLocal.
File edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::getFile () [inline]
Definition at line 55 of file TabbedDocument.java.
References fileLocal.
void edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::setTabTitle (File file) [inline]
Definition at line 58 of file TabbedDocument.java.
References fileLocal, edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::getUntitledDocCount(), tabbedEditorLocal, and tabFileName.
Referenced by TabbedDocument().
String edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::getTabTitle () [inline]
Definition at line 73 of file TabbedDocument.java.
References tabFileName.
Referenced by edu::stanford::atom::sti::client::tabbededitor::TabbedEditor::addEditorTab().
int edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::getTabIndex () [inline]
Definition at line 76 of file TabbedDocument.java.
References tabIndex.
Referenced by edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::documentIsChanged().
void edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::setTabIndex (int index) [inline]
Definition at line 79 of file TabbedDocument.java.
References tabIndex.
Referenced by TabbedDocument().
javax.swing.JTextPane edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::getTextPane () [inline]
Definition at line 82 of file TabbedDocument.java.
References textPaneLocal.
javax.swing.JScrollPane edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::getScrollPane () [inline]
Returns this document's scroll pane
Returns:
Definition at line 90 of file TabbedDocument.java.
References scrollPaneLocal.
void edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::setModifed (boolean Modified) [inline]
Definition at line 94 of file TabbedDocument.java.
References modified.
Referenced by edu::stanford::atom::sti::client::tabbededitor::tabDocumentListener::documentIsChanged().
boolean edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::isModifed () [inline]
Definition at line 98 of file TabbedDocument.java.
References modified.
String edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::getCaretLabelText () [inline]
Definition at line 102 of file TabbedDocument.java.
References caretListenerLocal, and edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::getText().
Member Data Documentation
String edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::tabFileName [private]
Definition at line 107 of file TabbedDocument.java.
Referenced by getTabTitle(), and setTabTitle().
javax.swing.JScrollPane edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::scrollPaneLocal = new javax.swing.JScrollPane() [private]
Definition at line 108 of file TabbedDocument.java.
Referenced by generateTab(), and getScrollPane().
javax.swing.JTextPane edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::textPaneLocal = new javax.swing.JTextPane() [private]
Definition at line 109 of file TabbedDocument.java.
Referenced by generateTab(), getTextPane(), and TabbedDocument().
File edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::fileLocal [private]
Definition at line 111 of file TabbedDocument.java.
Referenced by getFile(), setFile(), setTabTitle(), and TabbedDocument().
int edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::tabIndex [private]
Definition at line 112 of file TabbedDocument.java.
Referenced by getTabIndex(), and setTabIndex().
boolean edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::modified [private]
Definition at line 113 of file TabbedDocument.java.
Referenced by isModifed(), and setModifed().
CaretListenerLabel edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::caretListenerLocal [private]
Definition at line 115 of file TabbedDocument.java.
Referenced by generateTab(), getCaretLabelText(), and TabbedDocument().
AbstractDocument edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::abstractDocumentLocal [private]
Definition at line 116 of file TabbedDocument.java.
Referenced by TabbedDocument().
TabbedEditor edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::tabbedEditorLocal [private]
Definition at line 118 of file TabbedDocument.java.
Referenced by setTabTitle(), and TabbedDocument().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/tabbededitor/TabbedDocument.java