Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper
edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TEvent[] that)
static
edu.stanford.atom.sti.client.comm.corba.TEvent[] extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TEvent[] read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TEvent[] value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TEventSeq:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/TEventSeqHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TEventSeqHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TEvent[] that) [inline, static]
Definition at line 15 of file TEventSeqHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TEvent [] edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TEventSeqHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper::type () [inline, static]
Definition at line 29 of file TEventSeqHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper::id () [inline, static]
Definition at line 40 of file TEventSeqHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TEvent [] edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 45 of file TEventSeqHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TEvent::TEvent().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TEvent[] value) [inline, static]
Definition at line 55 of file TEventSeqHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper::_id = "IDL:Timing_Server/TEventSeq:1.0" [static, private]
Definition at line 13 of file TEventSeqHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper::__typeCode = null [static, private]
Definition at line 28 of file TEventSeqHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TEventSeqHelper.java