Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper
edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TVariable[] that)
static
edu.stanford.atom.sti.client.comm.corba.TVariable[] extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TVariable[] read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TVariable[] value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TVariableSeq:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/TVariableSeqHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TVariableSeqHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TVariable[] that) [inline, static]
Definition at line 15 of file TVariableSeqHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TVariable [] edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TVariableSeqHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper::type () [inline, static]
Definition at line 29 of file TVariableSeqHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper::id () [inline, static]
Definition at line 40 of file TVariableSeqHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TVariable [] edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 45 of file TVariableSeqHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TVariable::TVariable().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TVariable[] value) [inline, static]
Definition at line 55 of file TVariableSeqHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper::_id = "IDL:Timing_Server/TVariableSeq:1.0" [static, private]
Definition at line 13 of file TVariableSeqHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TVariableSeqHelper::__typeCode = null [static, private]
Definition at line 28 of file TVariableSeqHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TVariableSeqHelper.java