Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::ControlHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::ControlHelper
edu::stanford::atom::sti::client::comm::corba::ControlHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.Control that)
static
edu.stanford.atom.sti.client.comm.corba.Control extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.Control read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.Control value)
static
edu.stanford.atom.sti.client.comm.corba.Control narrow (org.omg.CORBA.Object obj)
static
edu.stanford.atom.sti.client.comm.corba.Control unchecked_narrow (org.omg.CORBA.Object obj)
Static Private Attributes
static String _id = "IDL:Timing_Server/Control:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/ControlHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:01 PM PDT
Definition at line 11 of file ControlHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::ControlHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.Control that) [inline, static]
Definition at line 15 of file ControlHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.Control edu::stanford::atom::sti::client::comm::corba::ControlHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file ControlHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::ControlHelper::type () [inline, static]
Definition at line 29 of file ControlHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::ControlHelper::id () [inline, static]
Definition at line 38 of file ControlHelper.java.
References _id.
Referenced by narrow().
static edu.stanford.atom.sti.client.comm.corba.Control edu::stanford::atom::sti::client::comm::corba::ControlHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 43 of file ControlHelper.java.
References narrow().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::ControlHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.Control value) [inline, static]
Definition at line 48 of file ControlHelper.java.
Referenced by insert().
static edu.stanford.atom.sti.client.comm.corba.Control edu::stanford::atom::sti::client::comm::corba::ControlHelper::narrow (org.omg.CORBA.Object obj) [inline, static]
Definition at line 53 of file ControlHelper.java.
References id().
Referenced by read().
static edu.stanford.atom.sti.client.comm.corba.Control edu::stanford::atom::sti::client::comm::corba::ControlHelper::unchecked_narrow (org.omg.CORBA.Object obj) [inline, static]
Definition at line 70 of file ControlHelper.java.
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::ControlHelper::_id = "IDL:Timing_Server/Control:1.0" [static, private]
Definition at line 13 of file ControlHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::ControlHelper::__typeCode = null [static, private]
Definition at line 28 of file ControlHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/ControlHelper.java