Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper
edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TRow[] that)
static
edu.stanford.atom.sti.client.comm.corba.TRow[] extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TRow[] read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TRow[] value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TRowSeq:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/TRowSeqHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:01 PM PDT
Definition at line 11 of file TRowSeqHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TRow[] that) [inline, static]
Definition at line 15 of file TRowSeqHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TRow [] edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TRowSeqHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper::type () [inline, static]
Definition at line 29 of file TRowSeqHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper::id () [inline, static]
Definition at line 40 of file TRowSeqHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TRow [] edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 45 of file TRowSeqHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TRow::TRow().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TRow[] value) [inline, static]
Definition at line 55 of file TRowSeqHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper::_id = "IDL:Timing_Server/TRowSeq:1.0" [static, private]
Definition at line 13 of file TRowSeqHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TRowSeqHelper::__typeCode = null [static, private]
Definition at line 28 of file TRowSeqHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TRowSeqHelper.java