Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TPosition Class Reference
edu::stanford::atom::sti::client::comm::corba::TPosition
edu::stanford::atom::sti::client::comm::corba::TPosition Class Reference
Public Member Functions
TPosition ()
TPosition (short _file, int _line)
Public Attributes
short file = (short)0
int line = (int)0
Detailed Description
Timing_Server/TPosition.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TPosition.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::comm::corba::TPosition::TPosition () [inline]
Definition at line 18 of file TPosition.java.
Referenced by edu::stanford::atom::sti::client::comm::corba::TPositionHelper::read().
edu::stanford::atom::sti::client::comm::corba::TPosition::TPosition (short _file, int _line) [inline]
Definition at line 22 of file TPosition.java.
References file, and line.
Member Data Documentation
short edu::stanford::atom::sti::client::comm::corba::TPosition::file = (short)0
Definition at line 13 of file TPosition.java.
Referenced by TPosition().
int edu::stanford::atom::sti::client::comm::corba::TPosition::line = (int)0
Definition at line 16 of file TPosition.java.
Referenced by TPosition().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TPosition.java