Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TValMixedHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TValMixedHelper
edu::stanford::atom::sti::client::comm::corba::TValMixedHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TValMixed that)
static
edu.stanford.atom.sti.client.comm.corba.TValMixed extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TValMixed read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TValMixed value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TValMixed/TValMixed:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/TValMixedHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TValMixedHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TValMixedHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TValMixed that) [inline, static]
Definition at line 15 of file TValMixedHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TValMixed edu::stanford::atom::sti::client::comm::corba::TValMixedHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TValMixedHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TValMixedHelper::type () [inline, static]
Definition at line 29 of file TValMixedHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TValMixedHelper::id () [inline, static]
Definition at line 73 of file TValMixedHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TValMixed edu::stanford::atom::sti::client::comm::corba::TValMixedHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 78 of file TValMixedHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TValMixed::TValMixed().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TValMixedHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TValMixed value) [inline, static]
Definition at line 104 of file TValMixedHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TValMixedHelper::_id = "IDL:Timing_Server/TValMixed/TValMixed:1.0" [static, private]
Definition at line 13 of file TValMixedHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TValMixedHelper::__typeCode = null [static, private]
Definition at line 28 of file TValMixedHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TValMixedHelper.java