Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper
edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TStatusLevel that)
static
edu.stanford.atom.sti.client.comm.corba.TStatusLevel extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TStatusLevel read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TStatusLevel value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TStatusLevel:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/TStatusLevelHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TStatusLevelHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TStatusLevel that) [inline, static]
Definition at line 15 of file TStatusLevelHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TStatusLevel edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TStatusLevelHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper::type () [inline, static]
Definition at line 29 of file TStatusLevelHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper::id () [inline, static]
Definition at line 38 of file TStatusLevelHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TStatusLevel edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 43 of file TStatusLevelHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TStatusLevel::TStatusLevel().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TStatusLevel value) [inline, static]
Definition at line 48 of file TStatusLevelHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper::_id = "IDL:Timing_Server/TStatusLevel:1.0" [static, private]
Definition at line 13 of file TStatusLevelHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TStatusLevelHelper::__typeCode = null [static, private]
Definition at line 28 of file TStatusLevelHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TStatusLevelHelper.java