Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TVariableHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TVariableHelper
edu::stanford::atom::sti::client::comm::corba::TVariableHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TVariable that)
static
edu.stanford.atom.sti.client.comm.corba.TVariable extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TVariable read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TVariable value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TVariable/TVariable:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
static boolean __active = false
Detailed Description
Timing_Server/TVariableHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TVariableHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TVariableHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TVariable that) [inline, static]
Definition at line 15 of file TVariableHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TVariable edu::stanford::atom::sti::client::comm::corba::TVariableHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TVariableHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TVariableHelper::type () [inline, static]
Definition at line 30 of file TVariableHelper.java.
References __active, __typeCode, and _id.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TVariableHelper::id () [inline, static]
Definition at line 68 of file TVariableHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TVariable edu::stanford::atom::sti::client::comm::corba::TVariableHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 73 of file TVariableHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TVariable::TVariable().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TVariableHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TVariable value) [inline, static]
Definition at line 82 of file TVariableHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TVariableHelper::_id = "IDL:Timing_Server/TVariable/TVariable:1.0" [static, private]
Definition at line 13 of file TVariableHelper.java.
Referenced by id(), and type().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TVariableHelper::__typeCode = null [static, private]
Definition at line 28 of file TVariableHelper.java.
Referenced by type().
boolean edu::stanford::atom::sti::client::comm::corba::TVariableHelper::__active = false [static, private]
Definition at line 29 of file TVariableHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TVariableHelper.java