Stanford Timing Interface: Client: edu::stanford::atom::sti::client::gui::table::CreateTable Class Reference
edu::stanford::atom::sti::client::gui::table::CreateTable
edu::stanford::atom::sti::client::gui::table::CreateTable Class Reference
Public Member Functions
CreateTable ()
CreateTable (Vector< Object[]> tableDataIn)
CreateTable (Vector< Object[]> tableDataIn, String[] colNamesIn)
CreateTable (Vector< Object[]> tableDataIn, Object[][] colNamesIn)
CreateTable (Vector< Object[]> tableDataIn, Object[][] colNamesIn, Object[][] tableOptionsIn)
void addObject (Object[] newRow)
String[] retrieveColumnNames ()
void setFilterField (JTextField jTF, Document filterDocument)
void filterColumnSelectionEvent (java.awt.event.ActionEvent evt)
Private Member Functions
int[] editableColumns ()
Object[][] defaultColumnNames (int arraySize)
Object[][] columnNamesStrToObj (String[] colNamesStr)
Object[][] defaultOptions ()
void newFilter ()
Private Attributes
Vector< Object[]> tableData
Object[][] columnNamesObj
Object[][] tableOptions
GuiTableModel newTableModel = new GuiTableModel()
TableRowSorter
< GuiTableModel > newSorter
JTextField filterField
int filterByColumn = 0
Detailed Description
Author:
Jonathan Harvey
Version:
1.0
See also:
javax.swing
javax.swing.JTable
Definition at line 43 of file CreateTable.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::gui::table::CreateTable::CreateTable () [inline]
Constructor
Definition at line 57 of file CreateTable.java.
edu::stanford::atom::sti::client::gui::table::CreateTable::CreateTable (Vector< Object[]> tableDataIn) [inline]
Constructor
Definition at line 71 of file CreateTable.java.
References defaultColumnNames(), and defaultOptions().
edu::stanford::atom::sti::client::gui::table::CreateTable::CreateTable (Vector< Object[]> tableDataIn, String[] colNamesIn) [inline]
Constructor
Definition at line 78 of file CreateTable.java.
References columnNamesStrToObj(), and defaultOptions().
edu::stanford::atom::sti::client::gui::table::CreateTable::CreateTable (Vector< Object[]> tableDataIn, Object colNamesIn[][]) [inline]
Constructor
Definition at line 87 of file CreateTable.java.
References defaultOptions().
edu::stanford::atom::sti::client::gui::table::CreateTable::CreateTable (Vector< Object[]> tableDataIn, Object colNamesIn[][], Object tableOptionsIn[][]) [inline]
Constructor
Definition at line 93 of file CreateTable.java.
References columnNamesObj, editableColumns(), newSorter, newTableModel, retrieveColumnNames(), edu::stanford::atom::sti::client::gui::table::GuiTableModel::setModelData(), tableData, and tableOptions.
Member Function Documentation
void edu::stanford::atom::sti::client::gui::table::CreateTable::addObject (Object[] newRow) [inline]
Definition at line 167 of file CreateTable.java.
References edu::stanford::atom::sti::client::gui::table::GuiTableModel::getModelData(), newTableModel, and edu::stanford::atom::sti::client::gui::table::GuiTableModel::setChangedData().
String [] edu::stanford::atom::sti::client::gui::table::CreateTable::retrieveColumnNames () [inline]
Definition at line 173 of file CreateTable.java.
References columnNamesObj.
Referenced by CreateTable().
int [] edu::stanford::atom::sti::client::gui::table::CreateTable::editableColumns () [inline, private]
Definition at line 187 of file CreateTable.java.
References columnNamesObj.
Referenced by CreateTable().
Object [][] edu::stanford::atom::sti::client::gui::table::CreateTable::defaultColumnNames (int arraySize) [inline, private]
Definition at line 222 of file CreateTable.java.
Referenced by CreateTable().
Object [][] edu::stanford::atom::sti::client::gui::table::CreateTable::columnNamesStrToObj (String[] colNamesStr) [inline, private]
Definition at line 231 of file CreateTable.java.
Referenced by CreateTable().
Object [][] edu::stanford::atom::sti::client::gui::table::CreateTable::defaultOptions () [inline, private]
Definition at line 241 of file CreateTable.java.
Referenced by CreateTable().
void edu::stanford::atom::sti::client::gui::table::CreateTable::setFilterField (JTextField jTF, Document filterDocument) [inline]
Definition at line 254 of file CreateTable.java.
References filterField, and newFilter().
void edu::stanford::atom::sti::client::gui::table::CreateTable::newFilter () [inline, private]
Definition at line 271 of file CreateTable.java.
References filterByColumn, filterField, and newSorter.
Referenced by setFilterField().
void edu::stanford::atom::sti::client::gui::table::CreateTable::filterColumnSelectionEvent (java.awt.event.ActionEvent evt) [inline]
Definition at line 291 of file CreateTable.java.
References filterByColumn.
Member Data Documentation
Vector<Object[]> edu::stanford::atom::sti::client::gui::table::CreateTable::tableData [private]
Definition at line 45 of file CreateTable.java.
Referenced by CreateTable().
Object [][] edu::stanford::atom::sti::client::gui::table::CreateTable::columnNamesObj [private]
Definition at line 46 of file CreateTable.java.
Referenced by CreateTable(), editableColumns(), and retrieveColumnNames().
Object [][] edu::stanford::atom::sti::client::gui::table::CreateTable::tableOptions [private]
Definition at line 47 of file CreateTable.java.
Referenced by CreateTable().
GuiTableModel edu::stanford::atom::sti::client::gui::table::CreateTable::newTableModel = new GuiTableModel() [private]
Definition at line 49 of file CreateTable.java.
Referenced by addObject(), and CreateTable().
TableRowSorter<GuiTableModel> edu::stanford::atom::sti::client::gui::table::CreateTable::newSorter [private]
Definition at line 51 of file CreateTable.java.
Referenced by CreateTable(), and newFilter().
JTextField edu::stanford::atom::sti::client::gui::table::CreateTable::filterField [private]
Definition at line 53 of file CreateTable.java.
Referenced by newFilter(), and setFilterField().
int edu::stanford::atom::sti::client::gui::table::CreateTable::filterByColumn = 0 [private]
Definition at line 54 of file CreateTable.java.
Referenced by filterColumnSelectionEvent(), and newFilter().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/gui/table/CreateTable.java