Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper
edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TChannel[] that)
static
edu.stanford.atom.sti.client.comm.corba.TChannel[] extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TChannel[] read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TChannel[] value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TChannelSeq:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/TChannelSeqHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TChannelSeqHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TChannel[] that) [inline, static]
Definition at line 15 of file TChannelSeqHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TChannel [] edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TChannelSeqHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper::type () [inline, static]
Definition at line 29 of file TChannelSeqHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper::id () [inline, static]
Definition at line 40 of file TChannelSeqHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TChannel [] edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 45 of file TChannelSeqHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TChannel::TChannel().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TChannel[] value) [inline, static]
Definition at line 55 of file TChannelSeqHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper::_id = "IDL:Timing_Server/TChannelSeq:1.0" [static, private]
Definition at line 13 of file TChannelSeqHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper::__typeCode = null [static, private]
Definition at line 28 of file TChannelSeqHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TChannelSeqHelper.java