Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub Class Reference
edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub
edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub Class Reference
Public Member Functions
String controller ()
void controller (String newController)
boolean requestPending ()
void requestPending (boolean newRequestPending)
String requesterName ()
void requesterName (String newRequesterName)
boolean requestControl (String myName)
void answerRequest (boolean yield)
String[] _ids ()
Private Member Functions
void readObject (java.io.ObjectInputStream s) throws java.io.IOException
void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
Static Private Attributes
static String[] __ids
Detailed Description
Timing_Server/_ModeHandlerStub.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file _ModeHandlerStub.java.
Member Function Documentation
String edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::controller () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations.
Definition at line 14 of file _ModeHandlerStub.java.
Referenced by controller().
void edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::controller (String newController) [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations.
Definition at line 33 of file _ModeHandlerStub.java.
References controller().
boolean edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::requestPending () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations.
Definition at line 52 of file _ModeHandlerStub.java.
Referenced by requestPending().
void edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::requestPending (boolean newRequestPending) [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations.
Definition at line 71 of file _ModeHandlerStub.java.
References requestPending().
String edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::requesterName () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations.
Definition at line 90 of file _ModeHandlerStub.java.
Referenced by requesterName().
void edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::requesterName (String newRequesterName) [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations.
Definition at line 109 of file _ModeHandlerStub.java.
References requesterName().
boolean edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::requestControl (String myName) [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations.
Definition at line 130 of file _ModeHandlerStub.java.
void edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::answerRequest (boolean yield) [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations.
Definition at line 150 of file _ModeHandlerStub.java.
String [] edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::_ids () [inline]
Definition at line 173 of file _ModeHandlerStub.java.
References __ids.
void edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::readObject (java.io.ObjectInputStream s) throws java.io.IOException [inline, private]
Definition at line 178 of file _ModeHandlerStub.java.
void edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::writeObject (java.io.ObjectOutputStream s) throws java.io.IOException [inline, private]
Definition at line 188 of file _ModeHandlerStub.java.
Member Data Documentation
String [] edu::stanford::atom::sti::client::comm::corba::_ModeHandlerStub::__ids [static, private]
Initial value:
 {
    "IDL:Timing_Server/ModeHandler:1.0"}
Definition at line 170 of file _ModeHandlerStub.java.
Referenced by _ids().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/_ModeHandlerStub.java