Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TEventHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TEventHelper
edu::stanford::atom::sti::client::comm::corba::TEventHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TEvent that)
static
edu.stanford.atom.sti.client.comm.corba.TEvent extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TEvent read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TEvent value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TEvent/TEvent:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
static boolean __active = false
Detailed Description
Timing_Server/TEventHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TEventHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TEventHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TEvent that) [inline, static]
Definition at line 15 of file TEventHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TEvent edu::stanford::atom::sti::client::comm::corba::TEventHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TEventHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TEventHelper::type () [inline, static]
Definition at line 30 of file TEventHelper.java.
References __active, __typeCode, and _id.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TEventHelper::id () [inline, static]
Definition at line 73 of file TEventHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TEvent edu::stanford::atom::sti::client::comm::corba::TEventHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 78 of file TEventHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TEvent::TEvent().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TEventHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TEvent value) [inline, static]
Definition at line 88 of file TEventHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TEventHelper::_id = "IDL:Timing_Server/TEvent/TEvent:1.0" [static, private]
Definition at line 13 of file TEventHelper.java.
Referenced by id(), and type().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TEventHelper::__typeCode = null [static, private]
Definition at line 28 of file TEventHelper.java.
Referenced by type().
boolean edu::stanford::atom::sti::client::comm::corba::TEventHelper::__active = false [static, private]
Definition at line 29 of file TEventHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TEventHelper.java