Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TChannel Class Reference
edu::stanford::atom::sti::client::comm::corba::TChannel
edu::stanford::atom::sti::client::comm::corba::TChannel Class Reference
Public Member Functions
TChannel ()
TChannel (edu.stanford.atom.sti.client.comm.corba.TBoard _board, short _channel)
Public Attributes
edu.stanford.atom.sti.client.comm.corba.TBoard board = null
short channel = (short)0
Detailed Description
Timing_Server/TChannel.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TChannel.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::comm::corba::TChannel::TChannel () [inline]
Definition at line 16 of file TChannel.java.
Referenced by edu::stanford::atom::sti::client::comm::corba::TChannelSeqHelper::read(), and edu::stanford::atom::sti::client::comm::corba::TChannelHelper::read().
edu::stanford::atom::sti::client::comm::corba::TChannel::TChannel (edu.stanford.atom.sti.client.comm.corba.TBoard _board, short _channel) [inline]
Definition at line 20 of file TChannel.java.
References board, and channel.
Member Data Documentation
edu.stanford.atom.sti.client.comm.corba.TBoard edu::stanford::atom::sti::client::comm::corba::TChannel::board = null
Definition at line 13 of file TChannel.java.
Referenced by TChannel().
short edu::stanford::atom::sti::client::comm::corba::TChannel::channel = (short)0
Definition at line 14 of file TChannel.java.
Referenced by TChannel().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TChannel.java