Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::_ParserStub Class Reference
edu::stanford::atom::sti::client::comm::corba::_ParserStub
edu::stanford::atom::sti::client::comm::corba::_ParserStub Class Reference
Public Member Functions
edu.stanford.atom.sti.client.comm.corba.TOverwritten[] overwritten ()
void overwritten (edu.stanford.atom.sti.client.comm.corba.TOverwritten[] newOverwritten)
boolean lockOnParse ()
void lockOnParse (boolean newLockOnParse)
boolean parseFile (String filename)
boolean parseString (String code)
String outMsg ()
String errMsg ()
String mainFile ()
edu.stanford.atom.sti.client.comm.corba.TChannel[] channels ()
String[] files ()
edu.stanford.atom.sti.client.comm.corba.TVariable[] variables ()
edu.stanford.atom.sti.client.comm.corba.TEvent[] events ()
String[] _ids ()
Private Member Functions
void readObject (java.io.ObjectInputStream s) throws java.io.IOException
void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
Static Private Attributes
static String[] __ids
Detailed Description
Timing_Server/_ParserStub.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file _ParserStub.java.
Member Function Documentation
edu.stanford.atom.sti.client.comm.corba.TOverwritten [] edu::stanford::atom::sti::client::comm::corba::_ParserStub::overwritten () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 16 of file _ParserStub.java.
Referenced by overwritten().
void edu::stanford::atom::sti::client::comm::corba::_ParserStub::overwritten (edu.stanford.atom.sti.client.comm.corba.TOverwritten[] newOverwritten) [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 37 of file _ParserStub.java.
References overwritten().
boolean edu::stanford::atom::sti::client::comm::corba::_ParserStub::lockOnParse () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 56 of file _ParserStub.java.
Referenced by lockOnParse().
void edu::stanford::atom::sti::client::comm::corba::_ParserStub::lockOnParse (boolean newLockOnParse) [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 75 of file _ParserStub.java.
References lockOnParse().
boolean edu::stanford::atom::sti::client::comm::corba::_ParserStub::parseFile (String filename) [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 96 of file _ParserStub.java.
boolean edu::stanford::atom::sti::client::comm::corba::_ParserStub::parseString (String code) [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 116 of file _ParserStub.java.
String edu::stanford::atom::sti::client::comm::corba::_ParserStub::outMsg () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 138 of file _ParserStub.java.
String edu::stanford::atom::sti::client::comm::corba::_ParserStub::errMsg () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 157 of file _ParserStub.java.
String edu::stanford::atom::sti::client::comm::corba::_ParserStub::mainFile () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 176 of file _ParserStub.java.
edu.stanford.atom.sti.client.comm.corba.TChannel [] edu::stanford::atom::sti::client::comm::corba::_ParserStub::channels () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 195 of file _ParserStub.java.
String [] edu::stanford::atom::sti::client::comm::corba::_ParserStub::files () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 214 of file _ParserStub.java.
edu.stanford.atom.sti.client.comm.corba.TVariable [] edu::stanford::atom::sti::client::comm::corba::_ParserStub::variables () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 233 of file _ParserStub.java.
edu.stanford.atom.sti.client.comm.corba.TEvent [] edu::stanford::atom::sti::client::comm::corba::_ParserStub::events () [inline]
Implements edu::stanford::atom::sti::client::comm::corba::ParserOperations.
Definition at line 252 of file _ParserStub.java.
String [] edu::stanford::atom::sti::client::comm::corba::_ParserStub::_ids () [inline]
Definition at line 275 of file _ParserStub.java.
References __ids.
void edu::stanford::atom::sti::client::comm::corba::_ParserStub::readObject (java.io.ObjectInputStream s) throws java.io.IOException [inline, private]
Definition at line 280 of file _ParserStub.java.
void edu::stanford::atom::sti::client::comm::corba::_ParserStub::writeObject (java.io.ObjectOutputStream s) throws java.io.IOException [inline, private]
Definition at line 290 of file _ParserStub.java.
Member Data Documentation
String [] edu::stanford::atom::sti::client::comm::corba::_ParserStub::__ids [static, private]
Initial value:
 {
    "IDL:Timing_Server/Parser:1.0"}
Definition at line 272 of file _ParserStub.java.
Referenced by _ids().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/_ParserStub.java