Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TStatus Class Reference
edu::stanford::atom::sti::client::comm::corba::TStatus
edu::stanford::atom::sti::client::comm::corba::TStatus Class Reference
Public Member Functions
TStatus ()
TStatus (edu.stanford.atom.sti.client.comm.corba.TStatusLevel _level, double _curTime, int _curEvent, short _curCycle)
Public Attributes
edu.stanford.atom.sti.client.comm.corba.TStatusLevel level = null
double curTime = (double)0
int curEvent = (int)0
short curCycle = (short)0
Detailed Description
Timing_Server/TStatus.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TStatus.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::comm::corba::TStatus::TStatus () [inline]
Definition at line 18 of file TStatus.java.
Referenced by edu::stanford::atom::sti::client::comm::corba::TStatusHelper::read().
edu::stanford::atom::sti::client::comm::corba::TStatus::TStatus (edu.stanford.atom.sti.client.comm.corba.TStatusLevel _level, double _curTime, int _curEvent, short _curCycle) [inline]
Definition at line 22 of file TStatus.java.
References curCycle, curEvent, curTime, and level.
Member Data Documentation
edu.stanford.atom.sti.client.comm.corba.TStatusLevel edu::stanford::atom::sti::client::comm::corba::TStatus::level = null
Definition at line 13 of file TStatus.java.
Referenced by TStatus().
double edu::stanford::atom::sti::client::comm::corba::TStatus::curTime = (double)0
Definition at line 14 of file TStatus.java.
Referenced by TStatus().
int edu::stanford::atom::sti::client::comm::corba::TStatus::curEvent = (int)0
Definition at line 15 of file TStatus.java.
Referenced by TStatus().
short edu::stanford::atom::sti::client::comm::corba::TStatus::curCycle = (short)0
Definition at line 16 of file TStatus.java.
Referenced by TStatus().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TStatus.java