Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TPositionHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TPositionHelper
edu::stanford::atom::sti::client::comm::corba::TPositionHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TPosition that)
static
edu.stanford.atom.sti.client.comm.corba.TPosition extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TPosition read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TPosition value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TPosition/TPosition:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
static boolean __active = false
Detailed Description
Timing_Server/TPositionHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TPositionHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TPositionHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TPosition that) [inline, static]
Definition at line 15 of file TPositionHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TPosition edu::stanford::atom::sti::client::comm::corba::TPositionHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TPositionHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TPositionHelper::type () [inline, static]
Definition at line 30 of file TPositionHelper.java.
References __active, __typeCode, and _id.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TPositionHelper::id () [inline, static]
Definition at line 63 of file TPositionHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TPosition edu::stanford::atom::sti::client::comm::corba::TPositionHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 68 of file TPositionHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TPosition::TPosition().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TPositionHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TPosition value) [inline, static]
Definition at line 76 of file TPositionHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TPositionHelper::_id = "IDL:Timing_Server/TPosition/TPosition:1.0" [static, private]
Definition at line 13 of file TPositionHelper.java.
Referenced by id(), and type().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TPositionHelper::__typeCode = null [static, private]
Definition at line 28 of file TPositionHelper.java.
Referenced by type().
boolean edu::stanford::atom::sti::client::comm::corba::TPositionHelper::__active = false [static, private]
Definition at line 29 of file TPositionHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TPositionHelper.java