Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper
edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TOverwritten that)
static
edu.stanford.atom.sti.client.comm.corba.TOverwritten extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TOverwritten read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TOverwritten value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TOverwritten/TOverwritten:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
static boolean __active = false
Detailed Description
Timing_Server/TOverwrittenHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TOverwrittenHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TOverwritten that) [inline, static]
Definition at line 15 of file TOverwrittenHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TOverwritten edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TOverwrittenHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper::type () [inline, static]
Definition at line 30 of file TOverwrittenHelper.java.
References __active, __typeCode, and _id.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper::id () [inline, static]
Definition at line 63 of file TOverwrittenHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TOverwritten edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 68 of file TOverwrittenHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TOverwritten::TOverwritten().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TOverwritten value) [inline, static]
Definition at line 76 of file TOverwrittenHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper::_id = "IDL:Timing_Server/TOverwritten/TOverwritten:1.0" [static, private]
Definition at line 13 of file TOverwrittenHelper.java.
Referenced by id(), and type().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper::__typeCode = null [static, private]
Definition at line 28 of file TOverwrittenHelper.java.
Referenced by type().
boolean edu::stanford::atom::sti::client::comm::corba::TOverwrittenHelper::__active = false [static, private]
Definition at line 29 of file TOverwrittenHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TOverwrittenHelper.java