Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::io::DummyTimingClient Class Reference
edu::stanford::atom::sti::client::comm::io::DummyTimingClient
edu::stanford::atom::sti::client::comm::io::DummyTimingClient Class Reference
Static Public Member Functions
static void main (String[] args)
Static Package Functions
static void getFromParser (ORB orb)
static void getFromModeHandler (ORB orb)
Static Package Attributes
static String hostAddr = "171.64.58.36"
static String corbaServerPort = "2809"
Detailed Description
Author:
Jason Hogan, Jonathan Harvey
Definition at line 21 of file DummyTimingClient.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::io::DummyTimingClient::main (String[] args) [inline, static]
Definition at line 30 of file DummyTimingClient.java.
References corbaServerPort, getFromModeHandler(), getFromParser(), and hostAddr.
static void edu::stanford::atom::sti::client::comm::io::DummyTimingClient::getFromParser (ORB orb) [inline, static, package]
getFromParser()
A proof-of-concept method that gets information from the specified Parser.Object and spits it out to the system output. -- Jonathan Harvey (harv_at_stanford_dot_edu)
Parameters:
orb The orb to which this will attach
Definition at line 53 of file DummyTimingClient.java.
References edu::stanford::atom::sti::client::comm::corba::ParserOperations::channels(), corbaServerPort, edu::stanford::atom::sti::client::comm::corba::ControlOperations::errMsg(), edu::stanford::atom::sti::client::comm::corba::ParserOperations::events(), edu::stanford::atom::sti::client::comm::corba::ParserOperations::files(), hostAddr, and edu::stanford::atom::sti::client::comm::corba::ParserOperations::mainFile().
Referenced by main().
static void edu::stanford::atom::sti::client::comm::io::DummyTimingClient::getFromModeHandler (ORB orb) [inline, static, package]
getFromModeHandler()
A proof-of-concept method that gets information from the specified ModeHandler.Object and spits it out to the system output. -- Jason Hogan (hogan/at/stanford.edu), Jonathan Harvey (harv/at/stanford.edu)
Parameters:
orb The orb to which this will attach
Definition at line 112 of file DummyTimingClient.java.
References corbaServerPort, hostAddr, edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations::requesterName(), and edu::stanford::atom::sti::client::comm::corba::ModeHandlerOperations::requestPending().
Referenced by main().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::io::DummyTimingClient::hostAddr = "171.64.58.36" [static, package]
Parameters:
args the command line arguments
Definition at line 27 of file DummyTimingClient.java.
Referenced by getFromModeHandler(), getFromParser(), and main().
String edu::stanford::atom::sti::client::comm::io::DummyTimingClient::corbaServerPort = "2809" [static, package]
Definition at line 28 of file DummyTimingClient.java.
Referenced by getFromModeHandler(), getFromParser(), and main().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/io/DummyTimingClient.java