Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TValMixed Class Reference
edu::stanford::atom::sti::client::comm::corba::TValMixed
edu::stanford::atom::sti::client::comm::corba::TValMixed Class Reference
Public Member Functions
TValMixed ()
edu.stanford.atom.sti.client.comm.corba.TValue discriminator ()
double number ()
void number (double value)
void number (edu.stanford.atom.sti.client.comm.corba.TValue discriminator, double value)
String stringVal ()
void stringVal (String value)
void stringVal (edu.stanford.atom.sti.client.comm.corba.TValue discriminator, String value)
edu.stanford.atom.sti.client.comm.corba.TDDS triplet ()
void triplet (edu.stanford.atom.sti.client.comm.corba.TDDS value)
void triplet (edu.stanford.atom.sti.client.comm.corba.TValue discriminator, edu.stanford.atom.sti.client.comm.corba.TDDS value)
Private Member Functions
void verifynumber (edu.stanford.atom.sti.client.comm.corba.TValue discriminator)
void verifystringVal (edu.stanford.atom.sti.client.comm.corba.TValue discriminator)
void verifytriplet (edu.stanford.atom.sti.client.comm.corba.TValue discriminator)
Private Attributes
double ___number
String ___stringVal
edu.stanford.atom.sti.client.comm.corba.TDDS ___triplet
edu.stanford.atom.sti.client.comm.corba.TValue __discriminator
boolean __uninitialized = true
Detailed Description
Timing_Server/TValMixed.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TValMixed.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::comm::corba::TValMixed::TValMixed () [inline]
Definition at line 19 of file TValMixed.java.
Referenced by edu::stanford::atom::sti::client::comm::corba::TValMixedHelper::read().
Member Function Documentation
edu.stanford.atom.sti.client.comm.corba.TValue edu::stanford::atom::sti::client::comm::corba::TValMixed::discriminator () [inline]
Definition at line 23 of file TValMixed.java.
References __discriminator, and __uninitialized.
Referenced by number(), stringVal(), triplet(), verifynumber(), verifystringVal(), and verifytriplet().
double edu::stanford::atom::sti::client::comm::corba::TValMixed::number () [inline]
Definition at line 30 of file TValMixed.java.
References ___number, __discriminator, __uninitialized, and verifynumber().
void edu::stanford::atom::sti::client::comm::corba::TValMixed::number (double value) [inline]
Definition at line 38 of file TValMixed.java.
References ___number, __discriminator, __uninitialized, and edu::stanford::atom::sti::client::comm::corba::TValue::TValue().
void edu::stanford::atom::sti::client::comm::corba::TValMixed::number (edu.stanford.atom.sti.client.comm.corba.TValue discriminator, double value) [inline]
Definition at line 45 of file TValMixed.java.
References ___number, __discriminator, __uninitialized, discriminator(), and verifynumber().
void edu::stanford::atom::sti::client::comm::corba::TValMixed::verifynumber (edu.stanford.atom.sti.client.comm.corba.TValue discriminator) [inline, private]
Definition at line 53 of file TValMixed.java.
References discriminator(), and edu::stanford::atom::sti::client::comm::corba::TValue::TValue().
Referenced by number().
String edu::stanford::atom::sti::client::comm::corba::TValMixed::stringVal () [inline]
Definition at line 59 of file TValMixed.java.
References ___stringVal, __discriminator, __uninitialized, and verifystringVal().
void edu::stanford::atom::sti::client::comm::corba::TValMixed::stringVal (String value) [inline]
Definition at line 67 of file TValMixed.java.
References ___stringVal, __discriminator, __uninitialized, and edu::stanford::atom::sti::client::comm::corba::TValue::TValue().
void edu::stanford::atom::sti::client::comm::corba::TValMixed::stringVal (edu.stanford.atom.sti.client.comm.corba.TValue discriminator, String value) [inline]
Definition at line 74 of file TValMixed.java.
References ___stringVal, __discriminator, __uninitialized, discriminator(), and verifystringVal().
void edu::stanford::atom::sti::client::comm::corba::TValMixed::verifystringVal (edu.stanford.atom.sti.client.comm.corba.TValue discriminator) [inline, private]
Definition at line 82 of file TValMixed.java.
References discriminator(), and edu::stanford::atom::sti::client::comm::corba::TValue::TValue().
Referenced by stringVal().
edu.stanford.atom.sti.client.comm.corba.TDDS edu::stanford::atom::sti::client::comm::corba::TValMixed::triplet () [inline]
Definition at line 88 of file TValMixed.java.
References ___triplet, __discriminator, __uninitialized, and verifytriplet().
void edu::stanford::atom::sti::client::comm::corba::TValMixed::triplet (edu.stanford.atom.sti.client.comm.corba.TDDS value) [inline]
Definition at line 96 of file TValMixed.java.
References ___triplet, __discriminator, __uninitialized, and edu::stanford::atom::sti::client::comm::corba::TValue::TValue().
void edu::stanford::atom::sti::client::comm::corba::TValMixed::triplet (edu.stanford.atom.sti.client.comm.corba.TValue discriminator, edu.stanford.atom.sti.client.comm.corba.TDDS value) [inline]
Definition at line 103 of file TValMixed.java.
References ___triplet, __discriminator, __uninitialized, discriminator(), and verifytriplet().
void edu::stanford::atom::sti::client::comm::corba::TValMixed::verifytriplet (edu.stanford.atom.sti.client.comm.corba.TValue discriminator) [inline, private]
Definition at line 111 of file TValMixed.java.
References discriminator(), and edu::stanford::atom::sti::client::comm::corba::TValue::TValue().
Referenced by triplet().
Member Data Documentation
double edu::stanford::atom::sti::client::comm::corba::TValMixed::___number [private]
Definition at line 13 of file TValMixed.java.
Referenced by number().
String edu::stanford::atom::sti::client::comm::corba::TValMixed::___stringVal [private]
Definition at line 14 of file TValMixed.java.
Referenced by stringVal().
edu.stanford.atom.sti.client.comm.corba.TDDS edu::stanford::atom::sti::client::comm::corba::TValMixed::___triplet [private]
Definition at line 15 of file TValMixed.java.
Referenced by triplet().
edu.stanford.atom.sti.client.comm.corba.TValue edu::stanford::atom::sti::client::comm::corba::TValMixed::__discriminator [private]
Definition at line 16 of file TValMixed.java.
Referenced by discriminator(), number(), stringVal(), and triplet().
boolean edu::stanford::atom::sti::client::comm::corba::TValMixed::__uninitialized = true [private]
Definition at line 17 of file TValMixed.java.
Referenced by discriminator(), number(), stringVal(), and triplet().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TValMixed.java