Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper
edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.ModeHandler that)
static
edu.stanford.atom.sti.client.comm.corba.ModeHandler extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.ModeHandler read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.ModeHandler value)
static
edu.stanford.atom.sti.client.comm.corba.ModeHandler narrow (org.omg.CORBA.Object obj)
static
edu.stanford.atom.sti.client.comm.corba.ModeHandler unchecked_narrow (org.omg.CORBA.Object obj)
Static Private Attributes
static String _id = "IDL:Timing_Server/ModeHandler:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/ModeHandlerHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file ModeHandlerHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.ModeHandler that) [inline, static]
Definition at line 15 of file ModeHandlerHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.ModeHandler edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file ModeHandlerHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::type () [inline, static]
Definition at line 29 of file ModeHandlerHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::id () [inline, static]
Definition at line 38 of file ModeHandlerHelper.java.
References _id.
Referenced by narrow().
static edu.stanford.atom.sti.client.comm.corba.ModeHandler edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 43 of file ModeHandlerHelper.java.
References narrow().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.ModeHandler value) [inline, static]
Definition at line 48 of file ModeHandlerHelper.java.
Referenced by insert().
static edu.stanford.atom.sti.client.comm.corba.ModeHandler edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::narrow (org.omg.CORBA.Object obj) [inline, static]
Definition at line 53 of file ModeHandlerHelper.java.
References id().
Referenced by read().
static edu.stanford.atom.sti.client.comm.corba.ModeHandler edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::unchecked_narrow (org.omg.CORBA.Object obj) [inline, static]
Definition at line 70 of file ModeHandlerHelper.java.
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::_id = "IDL:Timing_Server/ModeHandler:1.0" [static, private]
Definition at line 13 of file ModeHandlerHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::ModeHandlerHelper::__typeCode = null [static, private]
Definition at line 28 of file ModeHandlerHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/ModeHandlerHelper.java