Stanford Timing Interface: Client: edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel Class Reference
edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel
edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel Class Reference
Public Member Functions
CaretListenerLabel (JLabel jLabel, JTextPane jTextPane)
void caretUpdate (CaretEvent e)
void setText (String text)
String getText ()
Protected Member Functions
void generateSelectionInfoString (final int dot, final int mark)
Private Member Functions
void generateCaretString (int dot, int mark)
Private Attributes
String caretString = "none"
javax.swing.JTextPane jTextPaneLocal
javax.swing.JLabel jLabelLocal
String newline = "\n"
Detailed Description
Author:
Owner
The Sun Java Tutorials -- "TextComponentDemo.java"
Definition at line 25 of file CaretListenerLabel.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::CaretListenerLabel (JLabel jLabel, JTextPane jTextPane) [inline]
Definition at line 28 of file CaretListenerLabel.java.
References jLabelLocal, and jTextPaneLocal.
Member Function Documentation
void edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::caretUpdate (CaretEvent e) [inline]
Definition at line 35 of file CaretListenerLabel.java.
References generateCaretString(), getText(), and jLabelLocal.
void edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::generateCaretString (int dot, int mark) [inline, private]
Definition at line 41 of file CaretListenerLabel.java.
References jTextPaneLocal, newline, and setText().
Referenced by caretUpdate().
void edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::generateSelectionInfoString (final int dot, final int mark) [inline, protected]
Definition at line 64 of file CaretListenerLabel.java.
References jTextPaneLocal, newline, and setText().
void edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::setText (String text) [inline]
Definition at line 86 of file CaretListenerLabel.java.
References caretString.
Referenced by generateCaretString(), and generateSelectionInfoString().
String edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::getText () [inline]
Definition at line 90 of file CaretListenerLabel.java.
References caretString.
Referenced by caretUpdate(), and edu::stanford::atom::sti::client::tabbededitor::TabbedDocument::getCaretLabelText().
Member Data Documentation
String edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::caretString = "none" [private]
Definition at line 94 of file CaretListenerLabel.java.
Referenced by getText(), and setText().
javax.swing.JTextPane edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::jTextPaneLocal [private]
Definition at line 95 of file CaretListenerLabel.java.
Referenced by CaretListenerLabel(), generateCaretString(), and generateSelectionInfoString().
javax.swing.JLabel edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::jLabelLocal [private]
Definition at line 96 of file CaretListenerLabel.java.
Referenced by CaretListenerLabel(), and caretUpdate().
String edu::stanford::atom::sti::client::tabbededitor::CaretListenerLabel::newline = "\n" [private]
Definition at line 97 of file CaretListenerLabel.java.
Referenced by generateCaretString(), and generateSelectionInfoString().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/tabbededitor/CaretListenerLabel.java