Stanford Timing Interface: Client: edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter Class Reference
edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter
edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter Class Reference
Public Member Functions
TabbedPlotter (javax.swing.JTextArea inputTextArea, javax.swing.JTabbedPane outputPane, javax.swing.JFrame jFrame)
void registerTabbedPane (javax.swing.JTabbedPane jTabbedPane)
void registerInputTextArea (javax.swing.JTextArea jTextArea)
void registerFrame (javax.swing.JFrame jFrame)
void registerCaretPositionLabel (javax.swing.JLabel caretPositionLabel)
void addPlotterTab (TabbedPlot tabbedPlot, String input)
void updatePlotterTab (String inputString)
void removePlotterTab ()
void removePlotterTab (int tabIndex) throws ArrayIndexOutOfBoundsException
void closeActiveTab ()
boolean closeFileInTab (int tabIndex) throws ArrayIndexOutOfBoundsException
void createNewTab (String input)
int getUntitledDocCount ()
Public Attributes
javax.swing.JLabel caretPositionLabelLocal
Private Member Functions
void tabbedPaneStateChanged (javax.swing.event.ChangeEvent evt)
void updateInputTextArea ()
Private Attributes
Vector< TabbedPlot > tabbedPlotVector = new Vector<TabbedPlot>()
int tabCount = 0
javax.swing.JTabbedPane outputPaneLocal
javax.swing.JFrame jFrameLocal
javax.swing.JTextArea inputTextAreaLocal
Detailed Description
Author:
harv
Definition at line 17 of file TabbedPlotter.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::TabbedPlotter (javax.swing.JTextArea inputTextArea, javax.swing.JTabbedPane outputPane, javax.swing.JFrame jFrame) [inline]
Parameters:
inputTextArea
outputPane
jFrame
Definition at line 32 of file TabbedPlotter.java.
References registerFrame(), registerInputTextArea(), registerTabbedPane(), tabbedPaneStateChanged(), and tabCount.
Member Function Documentation
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::registerTabbedPane (javax.swing.JTabbedPane jTabbedPane) [inline]
Parameters:
jTabbedPane
Definition at line 54 of file TabbedPlotter.java.
References outputPaneLocal.
Referenced by TabbedPlotter().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::registerInputTextArea (javax.swing.JTextArea jTextArea) [inline]
Parameters:
jTextArea
Definition at line 61 of file TabbedPlotter.java.
References inputTextAreaLocal.
Referenced by TabbedPlotter().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::registerFrame (javax.swing.JFrame jFrame) [inline]
Parameters:
jFrame
Definition at line 68 of file TabbedPlotter.java.
References jFrameLocal.
Referenced by TabbedPlotter().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::registerCaretPositionLabel (javax.swing.JLabel caretPositionLabel) [inline]
Parameters:
caretPositionLabel
Definition at line 75 of file TabbedPlotter.java.
References caretPositionLabelLocal.
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::tabbedPaneStateChanged (javax.swing.event.ChangeEvent evt) [inline, private]
Parameters:
evt
Definition at line 83 of file TabbedPlotter.java.
References updateInputTextArea().
Referenced by TabbedPlotter().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::updateInputTextArea () [inline, private]
If there is any active tab, set the input text area to the value from the Vector<String> corresponding to the functions plotted on that graph. Otherwise, if there is no active tab, set the input text area to null.
Definition at line 92 of file TabbedPlotter.java.
References inputTextAreaLocal, outputPaneLocal, and tabbedPlotVector.
Referenced by tabbedPaneStateChanged().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::addPlotterTab (TabbedPlot tabbedPlot, String input) [inline]
Parameters:
tabbedPlot
input
Definition at line 106 of file TabbedPlotter.java.
References edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::createTab(), edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::getTabTitle(), and outputPaneLocal.
Referenced by createNewTab().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::updatePlotterTab (String inputString) [inline]
Function to update the plot in the currently selected plotter tab.
Definition at line 113 of file TabbedPlotter.java.
References outputPaneLocal, edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlot::setActivePlot(), and tabbedPlotVector.
Referenced by edu::stanford::atom::sti::client::gui::PlotterGUI::buttonCurrentActionPerformed().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::removePlotterTab () [inline]
no documentation yet
Returns:
returnString
Definition at line 132 of file TabbedPlotter.java.
References outputPaneLocal.
Referenced by closeFileInTab().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::removePlotterTab (int tabIndex) throws ArrayIndexOutOfBoundsException [inline]
Definition at line 136 of file TabbedPlotter.java.
References outputPaneLocal, and tabbedPlotVector.
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::closeActiveTab () [inline]
Definition at line 153 of file TabbedPlotter.java.
References closeFileInTab(), and outputPaneLocal.
Referenced by edu::stanford::atom::sti::client::gui::PlotterGUI::buttonCloseActionPerformed(), and edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileCloseActionPerformed().
boolean edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::closeFileInTab (int tabIndex) throws ArrayIndexOutOfBoundsException [inline]
Generic close file method.
Parameters:
tabIndex The index of the JTabbedPane that contains the document to close
Returns:
true if the document closed successfully, false otherwise.
Exceptions:
java.lang.ArrayIndexOutOfBoundsException
Definition at line 166 of file TabbedPlotter.java.
References removePlotterTab(), and tabbedPlotVector.
Referenced by closeActiveTab().
void edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::createNewTab (String input) [inline]
Parameters:
input
Definition at line 181 of file TabbedPlotter.java.
References addPlotterTab(), outputPaneLocal, tabbedPlotVector, and tabCount.
Referenced by edu::stanford::atom::sti::client::gui::PlotterGUI::buttonNewActionPerformed(), and edu::stanford::atom::sti::client::gui::PlotterGUI::menuFileNewActionPerformed().
int edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::getUntitledDocCount () [inline]
Returns:
Definition at line 200 of file TabbedPlotter.java.
References tabCount.
Member Data Documentation
Vector<TabbedPlot> edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::tabbedPlotVector = new Vector<TabbedPlot>() [private]
Definition at line 19 of file TabbedPlotter.java.
Referenced by closeFileInTab(), createNewTab(), removePlotterTab(), updateInputTextArea(), and updatePlotterTab().
int edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::tabCount = 0 [private]
Definition at line 20 of file TabbedPlotter.java.
Referenced by createNewTab(), getUntitledDocCount(), and TabbedPlotter().
javax.swing.JLabel edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::caretPositionLabelLocal
Definition at line 21 of file TabbedPlotter.java.
Referenced by registerCaretPositionLabel().
javax.swing.JTabbedPane edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::outputPaneLocal [private]
Definition at line 22 of file TabbedPlotter.java.
Referenced by addPlotterTab(), closeActiveTab(), createNewTab(), registerTabbedPane(), removePlotterTab(), updateInputTextArea(), and updatePlotterTab().
javax.swing.JFrame edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::jFrameLocal [private]
Definition at line 23 of file TabbedPlotter.java.
Referenced by registerFrame().
javax.swing.JTextArea edu::stanford::atom::sti::client::gui::tabbedplotter::TabbedPlotter::inputTextAreaLocal [private]
Definition at line 24 of file TabbedPlotter.java.
Referenced by registerInputTextArea(), and updateInputTextArea().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/gui/tabbedplotter/TabbedPlotter.java