Stanford Timing Interface: Client: edu::stanford::atom::sti::client::gui::table::GuiTableModel Class Reference
edu::stanford::atom::sti::client::gui::table::GuiTableModel
edu::stanford::atom::sti::client::gui::table::GuiTableModel Class Reference
Public Member Functions
void setModelData (Vector< Object[]> vObj, String[] gStr, int[] eCol)
void setChangedData (Vector< Object[]> vObj)
Vector< Object[]> getModelData ()
int getColumnCount ()
int getRowCount ()
String getColumnName (int col)
Object getValueAt (int row, int col)
Class getColumnClass (int c)
boolean isCellEditable (int row, int col)
void setValueAt (Object value, int row, int col)
Private Member Functions
void printDebugData ()
Private Attributes
String[] columnNames
Vector< Object[]> data
int[] editableColumns = new int[0]
String errorColName = "Undefined Column"
Detailed Description
Author:
harv
Definition at line 20 of file GuiTableModel.java.
Member Function Documentation
void edu::stanford::atom::sti::client::gui::table::GuiTableModel::setModelData (Vector< Object[]> vObj, String[] gStr, int[] eCol) [inline]
Definition at line 28 of file GuiTableModel.java.
References columnNames, data, and editableColumns.
Referenced by edu::stanford::atom::sti::client::gui::table::CreateTable::CreateTable().
void edu::stanford::atom::sti::client::gui::table::GuiTableModel::setChangedData (Vector< Object[]> vObj) [inline]
Mutator method to change the data in the model.
Parameters:
vObj
Definition at line 46 of file GuiTableModel.java.
References data.
Referenced by edu::stanford::atom::sti::client::gui::table::CreateTable::addObject().
Vector<Object[]> edu::stanford::atom::sti::client::gui::table::GuiTableModel::getModelData () [inline]
Accessor method for model data vector
Returns:
Definition at line 55 of file GuiTableModel.java.
References data.
Referenced by edu::stanford::atom::sti::client::gui::table::CreateTable::addObject().
int edu::stanford::atom::sti::client::gui::table::GuiTableModel::getColumnCount () [inline]
Definition at line 67 of file GuiTableModel.java.
References columnNames.
Referenced by printDebugData().
int edu::stanford::atom::sti::client::gui::table::GuiTableModel::getRowCount () [inline]
Definition at line 71 of file GuiTableModel.java.
References data.
Referenced by printDebugData().
String edu::stanford::atom::sti::client::gui::table::GuiTableModel::getColumnName (int col) [inline]
Definition at line 76 of file GuiTableModel.java.
References columnNames.
Object edu::stanford::atom::sti::client::gui::table::GuiTableModel::getValueAt (int row, int col) [inline]
Definition at line 80 of file GuiTableModel.java.
References data.
Referenced by getColumnClass().
Class edu::stanford::atom::sti::client::gui::table::GuiTableModel::getColumnClass (int c) [inline]
Definition at line 92 of file GuiTableModel.java.
References getValueAt().
boolean edu::stanford::atom::sti::client::gui::table::GuiTableModel::isCellEditable (int row, int col) [inline]
Definition at line 102 of file GuiTableModel.java.
References editableColumns.
void edu::stanford::atom::sti::client::gui::table::GuiTableModel::setValueAt (Object value, int row, int col) [inline]
Definition at line 122 of file GuiTableModel.java.
References data, and printDebugData().
void edu::stanford::atom::sti::client::gui::table::GuiTableModel::printDebugData () [inline, private]
Definition at line 137 of file GuiTableModel.java.
References data, getColumnCount(), and getRowCount().
Referenced by setValueAt().
Member Data Documentation
String [] edu::stanford::atom::sti::client::gui::table::GuiTableModel::columnNames [private]
Definition at line 22 of file GuiTableModel.java.
Referenced by getColumnCount(), getColumnName(), and setModelData().
Vector<Object[]> edu::stanford::atom::sti::client::gui::table::GuiTableModel::data [private]
Definition at line 23 of file GuiTableModel.java.
Referenced by getModelData(), getRowCount(), getValueAt(), printDebugData(), setChangedData(), setModelData(), and setValueAt().
int [] edu::stanford::atom::sti::client::gui::table::GuiTableModel::editableColumns = new int[0] [private]
Definition at line 26 of file GuiTableModel.java.
Referenced by isCellEditable(), and setModelData().
String edu::stanford::atom::sti::client::gui::table::GuiTableModel::errorColName = "Undefined Column" [private]
Definition at line 65 of file GuiTableModel.java.
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/gui/table/GuiTableModel.java