Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper
edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.ExpSequence that)
static
edu.stanford.atom.sti.client.comm.corba.ExpSequence extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.ExpSequence read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.ExpSequence value)
static
edu.stanford.atom.sti.client.comm.corba.ExpSequence narrow (org.omg.CORBA.Object obj)
static
edu.stanford.atom.sti.client.comm.corba.ExpSequence unchecked_narrow (org.omg.CORBA.Object obj)
Static Private Attributes
static String _id = "IDL:Timing_Server/ExpSequence:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/ExpSequenceHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:01 PM PDT
Definition at line 11 of file ExpSequenceHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.ExpSequence that) [inline, static]
Definition at line 15 of file ExpSequenceHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.ExpSequence edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file ExpSequenceHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::type () [inline, static]
Definition at line 29 of file ExpSequenceHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::id () [inline, static]
Definition at line 38 of file ExpSequenceHelper.java.
References _id.
Referenced by narrow().
static edu.stanford.atom.sti.client.comm.corba.ExpSequence edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 43 of file ExpSequenceHelper.java.
References narrow().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.ExpSequence value) [inline, static]
Definition at line 48 of file ExpSequenceHelper.java.
Referenced by insert().
static edu.stanford.atom.sti.client.comm.corba.ExpSequence edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::narrow (org.omg.CORBA.Object obj) [inline, static]
Definition at line 53 of file ExpSequenceHelper.java.
References id().
Referenced by read().
static edu.stanford.atom.sti.client.comm.corba.ExpSequence edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::unchecked_narrow (org.omg.CORBA.Object obj) [inline, static]
Definition at line 70 of file ExpSequenceHelper.java.
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::_id = "IDL:Timing_Server/ExpSequence:1.0" [static, private]
Definition at line 13 of file ExpSequenceHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::ExpSequenceHelper::__typeCode = null [static, private]
Definition at line 28 of file ExpSequenceHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/ExpSequenceHelper.java