Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::ParserHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::ParserHelper
edu::stanford::atom::sti::client::comm::corba::ParserHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.Parser that)
static
edu.stanford.atom.sti.client.comm.corba.Parser extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.Parser read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.Parser value)
static
edu.stanford.atom.sti.client.comm.corba.Parser narrow (org.omg.CORBA.Object obj)
static
edu.stanford.atom.sti.client.comm.corba.Parser unchecked_narrow (org.omg.CORBA.Object obj)
Static Private Attributes
static String _id = "IDL:Timing_Server/Parser:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/ParserHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file ParserHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::ParserHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.Parser that) [inline, static]
Definition at line 15 of file ParserHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.Parser edu::stanford::atom::sti::client::comm::corba::ParserHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file ParserHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::ParserHelper::type () [inline, static]
Definition at line 29 of file ParserHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::ParserHelper::id () [inline, static]
Definition at line 38 of file ParserHelper.java.
References _id.
Referenced by narrow().
static edu.stanford.atom.sti.client.comm.corba.Parser edu::stanford::atom::sti::client::comm::corba::ParserHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 43 of file ParserHelper.java.
References narrow().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::ParserHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.Parser value) [inline, static]
Definition at line 48 of file ParserHelper.java.
Referenced by insert().
static edu.stanford.atom.sti.client.comm.corba.Parser edu::stanford::atom::sti::client::comm::corba::ParserHelper::narrow (org.omg.CORBA.Object obj) [inline, static]
Definition at line 53 of file ParserHelper.java.
References id().
Referenced by read().
static edu.stanford.atom.sti.client.comm.corba.Parser edu::stanford::atom::sti::client::comm::corba::ParserHelper::unchecked_narrow (org.omg.CORBA.Object obj) [inline, static]
Definition at line 70 of file ParserHelper.java.
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::ParserHelper::_id = "IDL:Timing_Server/Parser:1.0" [static, private]
Definition at line 13 of file ParserHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::ParserHelper::__typeCode = null [static, private]
Definition at line 28 of file ParserHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/ParserHelper.java