Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TEvent Class Reference
edu::stanford::atom::sti::client::comm::corba::TEvent
edu::stanford::atom::sti::client::comm::corba::TEvent Class Reference
Public Member Functions
TEvent ()
TEvent (short _channel, double _time, edu.stanford.atom.sti.client.comm.corba.TValMixed _value, edu.stanford.atom.sti.client.comm.corba.TPosition _pos)
Public Attributes
short channel = (short)0
double time = (double)0
edu.stanford.atom.sti.client.comm.corba.TValMixed value = null
edu.stanford.atom.sti.client.comm.corba.TPosition pos = null
Detailed Description
Timing_Server/TEvent.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TEvent.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::comm::corba::TEvent::TEvent () [inline]
Definition at line 20 of file TEvent.java.
Referenced by edu::stanford::atom::sti::client::comm::corba::TEventSeqHelper::read(), and edu::stanford::atom::sti::client::comm::corba::TEventHelper::read().
edu::stanford::atom::sti::client::comm::corba::TEvent::TEvent (short _channel, double _time, edu.stanford.atom.sti.client.comm.corba.TValMixed _value, edu.stanford.atom.sti.client.comm.corba.TPosition _pos) [inline]
Definition at line 24 of file TEvent.java.
References channel, pos, time, and value.
Member Data Documentation
short edu::stanford::atom::sti::client::comm::corba::TEvent::channel = (short)0
Definition at line 13 of file TEvent.java.
Referenced by TEvent().
double edu::stanford::atom::sti::client::comm::corba::TEvent::time = (double)0
Definition at line 16 of file TEvent.java.
Referenced by TEvent().
edu.stanford.atom.sti.client.comm.corba.TValMixed edu::stanford::atom::sti::client::comm::corba::TEvent::value = null
Definition at line 17 of file TEvent.java.
Referenced by TEvent().
edu.stanford.atom.sti.client.comm.corba.TPosition edu::stanford::atom::sti::client::comm::corba::TEvent::pos = null
Definition at line 18 of file TEvent.java.
Referenced by TEvent().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TEvent.java