Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TDDS Class Reference
edu::stanford::atom::sti::client::comm::corba::TDDS
edu::stanford::atom::sti::client::comm::corba::TDDS Class Reference
Public Member Functions
TDDS ()
TDDS (double _freq, double _phase, double _ampl)
Public Attributes
double freq = (double)0
double phase = (double)0
double ampl = (double)0
Detailed Description
Timing_Server/TDDS.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TDDS.java.
Constructor & Destructor Documentation
edu::stanford::atom::sti::client::comm::corba::TDDS::TDDS () [inline]
Definition at line 17 of file TDDS.java.
Referenced by edu::stanford::atom::sti::client::comm::corba::TDDSHelper::read().
edu::stanford::atom::sti::client::comm::corba::TDDS::TDDS (double _freq, double _phase, double _ampl) [inline]
Definition at line 21 of file TDDS.java.
References ampl, freq, and phase.
Member Data Documentation
double edu::stanford::atom::sti::client::comm::corba::TDDS::freq = (double)0
Definition at line 13 of file TDDS.java.
Referenced by TDDS().
double edu::stanford::atom::sti::client::comm::corba::TDDS::phase = (double)0
Definition at line 14 of file TDDS.java.
Referenced by TDDS().
double edu::stanford::atom::sti::client::comm::corba::TDDS::ampl = (double)0
Definition at line 15 of file TDDS.java.
Referenced by TDDS().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TDDS.java