Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper Class Reference
edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper
edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper Class Reference
Static Public Member Functions
static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TVarMixed that)
static
edu.stanford.atom.sti.client.comm.corba.TVarMixed extract (org.omg.CORBA.Any a)
synchronized static
org.omg.CORBA.TypeCode type ()
static String id ()
static
edu.stanford.atom.sti.client.comm.corba.TVarMixed read (org.omg.CORBA.portable.InputStream istream)
static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TVarMixed value)
Static Private Attributes
static String _id = "IDL:Timing_Server/TVarMixed/TVarMixed:1.0"
static
org.omg.CORBA.TypeCode __typeCode = null
Detailed Description
Timing_Server/TVarMixedHelper.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file TVarMixedHelper.java.
Member Function Documentation
static void edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper::insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TVarMixed that) [inline, static]
Definition at line 15 of file TVarMixedHelper.java.
References type(), and write().
static edu.stanford.atom.sti.client.comm.corba.TVarMixed edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper::extract (org.omg.CORBA.Any a) [inline, static]
Definition at line 23 of file TVarMixedHelper.java.
References read().
synchronized static org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper::type () [inline, static]
Definition at line 29 of file TVarMixedHelper.java.
References __typeCode.
Referenced by insert().
static String edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper::id () [inline, static]
Definition at line 83 of file TVarMixedHelper.java.
References _id.
static edu.stanford.atom.sti.client.comm.corba.TVarMixed edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper::read (org.omg.CORBA.portable.InputStream istream) [inline, static]
Definition at line 88 of file TVarMixedHelper.java.
References edu::stanford::atom::sti::client::comm::corba::TVarMixed::TVarMixed().
Referenced by extract().
static void edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper::write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TVarMixed value) [inline, static]
Definition at line 119 of file TVarMixedHelper.java.
Referenced by insert().
Member Data Documentation
String edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper::_id = "IDL:Timing_Server/TVarMixed/TVarMixed:1.0" [static, private]
Definition at line 13 of file TVarMixedHelper.java.
Referenced by id().
org.omg.CORBA.TypeCode edu::stanford::atom::sti::client::comm::corba::TVarMixedHelper::__typeCode = null [static, private]
Definition at line 28 of file TVarMixedHelper.java.
Referenced by type().
The documentation for this class was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/TVarMixedHelper.java