Stanford Timing Interface: Client: edu::stanford::atom::sti::client::comm::corba::ParserOperations Interface Reference
edu::stanford::atom::sti::client::comm::corba::ParserOperations
edu::stanford::atom::sti::client::comm::corba::ParserOperations Interface Reference
Public Member Functions
void overwritten (edu.stanford.atom.sti.client.comm.corba.TOverwritten[] newOverwritten)
boolean lockOnParse ()
void lockOnParse (boolean newLockOnParse)
boolean parseFile (String filename)
boolean parseString (String code)
String outMsg ()
String errMsg ()
String mainFile ()
edu.stanford.atom.sti.client.comm.corba.TChannel[] channels ()
String[] files ()
edu.stanford.atom.sti.client.comm.corba.TVariable[] variables ()
edu.stanford.atom.sti.client.comm.corba.TEvent[] events ()
Package Functions
edu.stanford.atom.sti.client.comm.corba.TOverwritten[] overwritten ()
Detailed Description
Timing_Server/ParserOperations.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from c:/code/Timing_Server/timingserver.idl Tuesday, April 29, 2008 9:27:00 PM PDT
Definition at line 11 of file ParserOperations.java.
Member Function Documentation
edu.stanford.atom.sti.client.comm.corba.TOverwritten [] edu::stanford::atom::sti::client::comm::corba::ParserOperations::overwritten () [package]
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
void edu::stanford::atom::sti::client::comm::corba::ParserOperations::overwritten (edu.stanford.atom.sti.client.comm.corba.TOverwritten[] newOverwritten)
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
boolean edu::stanford::atom::sti::client::comm::corba::ParserOperations::lockOnParse ()
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
void edu::stanford::atom::sti::client::comm::corba::ParserOperations::lockOnParse (boolean newLockOnParse)
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
boolean edu::stanford::atom::sti::client::comm::corba::ParserOperations::parseFile (String filename)
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
boolean edu::stanford::atom::sti::client::comm::corba::ParserOperations::parseString (String code)
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
String edu::stanford::atom::sti::client::comm::corba::ParserOperations::outMsg ()
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
String edu::stanford::atom::sti::client::comm::corba::ParserOperations::errMsg ()
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
String edu::stanford::atom::sti::client::comm::corba::ParserOperations::mainFile ()
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
Referenced by edu::stanford::atom::sti::client::comm::io::DummyTimingClient::getFromParser().
edu.stanford.atom.sti.client.comm.corba.TChannel [] edu::stanford::atom::sti::client::comm::corba::ParserOperations::channels ()
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
Referenced by edu::stanford::atom::sti::client::comm::io::DummyTimingClient::getFromParser().
String [] edu::stanford::atom::sti::client::comm::corba::ParserOperations::files ()
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
Referenced by edu::stanford::atom::sti::client::comm::io::DummyTimingClient::getFromParser().
edu.stanford.atom.sti.client.comm.corba.TVariable [] edu::stanford::atom::sti::client::comm::corba::ParserOperations::variables ()
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
edu.stanford.atom.sti.client.comm.corba.TEvent [] edu::stanford::atom::sti::client::comm::corba::ParserOperations::events ()
Implemented in edu::stanford::atom::sti::client::comm::corba::_ParserStub.
Referenced by edu::stanford::atom::sti::client::comm::io::DummyTimingClient::getFromParser().
The documentation for this interface was generated from the following file:
src/edu/stanford/atom/sti/client/comm/corba/ParserOperations.java