package edu.stanford.atom.sti.client.comm.corba;


/**
* edu/stanford/atom/sti/client/comm/corba/ControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./client.idl
* Thursday, September 4, 2008 10:42:39 AM PDT
*/

public interface ControlOperations 
{

  //        readonly attribute ExpSequence expSeq;
  String errMsg ();
  edu.stanford.atom.sti.client.comm.corba.TStatus status ();
  void reset ();
  void setDirect ();

  //Dataformat unknown!
  void runSingle ();

  //Uses Parser.overwritten as it currently is.
  void runSequence ();

  //Sets Parser.overwritten from Control.expSeq
  void _continue ();

  //Jumps to next entry in expSeq
  void stop ();
} // interface ControlOperations
