package edu.stanford.atom.sti.client.comm.corba;


/**
* Timing_Server/ModeHandler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/code/Timing_Server/timingserver.idl
* Tuesday, April 29, 2008 9:27:00 PM PDT
*/

public interface ModeHandler extends ModeHandlerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ModeHandler
