package edu.stanford.atom.sti.client.comm.corba;


/**
* Timing_Server/TChannel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/code/Timing_Server/timingserver.idl
* Tuesday, April 29, 2008 9:27:00 PM PDT
*/

public final class TChannel implements org.omg.CORBA.portable.IDLEntity
{
  public edu.stanford.atom.sti.client.comm.corba.TBoard board = null;
  public short channel = (short)0;

  public TChannel ()
  {
  } // ctor

  public TChannel (edu.stanford.atom.sti.client.comm.corba.TBoard _board, short _channel)
  {
    board = _board;
    channel = _channel;
  } // ctor

} // class TChannel
