package edu.stanford.atom.sti.client.comm.corba;


/**
* edu/stanford/atom/sti/client/comm/corba/TDDS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./client.idl
* Thursday, September 4, 2008 10:42:38 AM PDT
*/

public final class TDDS implements org.omg.CORBA.portable.IDLEntity
{
  public double freq = (double)0;
  public double phase = (double)0;
  public double ampl = (double)0;

  public TDDS ()
  {
  } // ctor

  public TDDS (double _freq, double _phase, double _ampl)
  {
    freq = _freq;
    phase = _phase;
    ampl = _ampl;
  } // ctor

} // class TDDS
