package edu.stanford.atom.sti.client.comm.corba;


/**
* edu/stanford/atom/sti/client/comm/corba/TEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./client.idl
* Thursday, September 4, 2008 10:42:38 AM PDT
*/

public final class TEvent implements org.omg.CORBA.portable.IDLEntity
{
  public short channel = (short)0;

  //References Parser.channels
  public double time = (double)0;
  public edu.stanford.atom.sti.client.comm.corba.TValMixed value = null;
  public edu.stanford.atom.sti.client.comm.corba.TPosition pos = null;

  public TEvent ()
  {
  } // ctor

  public TEvent (short _channel, double _time, edu.stanford.atom.sti.client.comm.corba.TValMixed _value, edu.stanford.atom.sti.client.comm.corba.TPosition _pos)
  {
    channel = _channel;
    time = _time;
    value = _value;
    pos = _pos;
  } // ctor

} // class TEvent
