package edu.stanford.atom.sti.client.comm.corba;


/**
* edu/stanford/atom/sti/client/comm/corba/TOverwritten.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./client.idl
* Sunday, August 10, 2008 10:54:00 AM PDT
*/

public final class TOverwritten implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String value = null;

  public TOverwritten ()
  {
  } // ctor

  public TOverwritten (String _name, String _value)
  {
    name = _name;
    value = _value;
  } // ctor

} // class TOverwritten
