package edu.stanford.atom.sti.client.comm.corba;


/**
* Timing_Server/TOverwritten.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/code/Timing_Server/timingserver.idl
* Tuesday, April 29, 2008 9:27:00 PM PDT
*/

public final class TOverwritten implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String value = null;

  public TOverwritten ()
  {
  } // ctor

  public TOverwritten (String _name, String _value)
  {
    name = _name;
    value = _value;
  } // ctor

} // class TOverwritten
