package edu.stanford.atom.sti.client.comm.corba;


/**
* edu/stanford/atom/sti/client/comm/corba/TStatusLevelHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./client.idl
* Sunday, August 10, 2008 10:54:00 AM PDT
*/

abstract public class TStatusLevelHelper
{
  private static String  _id = "IDL:STI_Client_Server/TStatusLevel:1.0";

  public static void insert (org.omg.CORBA.Any a, edu.stanford.atom.sti.client.comm.corba.TStatusLevel that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static edu.stanford.atom.sti.client.comm.corba.TStatusLevel extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (edu.stanford.atom.sti.client.comm.corba.TStatusLevelHelper.id (), "TStatusLevel", new String[] { "LevelStopped", "LevelRunning", "LevelPaused", "LevelError"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static edu.stanford.atom.sti.client.comm.corba.TStatusLevel read (org.omg.CORBA.portable.InputStream istream)
  {
    return edu.stanford.atom.sti.client.comm.corba.TStatusLevel.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, edu.stanford.atom.sti.client.comm.corba.TStatusLevel value)
  {
    ostream.write_long (value.value ());
  }

}
