package edu.stanford.atom.sti.client.comm.corba;


/**
* edu/stanford/atom/sti/client/comm/corba/TStatusLevel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./client.idl
* Tuesday, August 26, 2008 10:21:42 AM PDT
*/

public class TStatusLevel implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static edu.stanford.atom.sti.client.comm.corba.TStatusLevel[] __array = new edu.stanford.atom.sti.client.comm.corba.TStatusLevel [__size];

  public static final int _LevelStopped = 0;
  public static final edu.stanford.atom.sti.client.comm.corba.TStatusLevel LevelStopped = new edu.stanford.atom.sti.client.comm.corba.TStatusLevel(_LevelStopped);
  public static final int _LevelRunning = 1;
  public static final edu.stanford.atom.sti.client.comm.corba.TStatusLevel LevelRunning = new edu.stanford.atom.sti.client.comm.corba.TStatusLevel(_LevelRunning);
  public static final int _LevelPaused = 2;
  public static final edu.stanford.atom.sti.client.comm.corba.TStatusLevel LevelPaused = new edu.stanford.atom.sti.client.comm.corba.TStatusLevel(_LevelPaused);
  public static final int _LevelError = 3;
  public static final edu.stanford.atom.sti.client.comm.corba.TStatusLevel LevelError = new edu.stanford.atom.sti.client.comm.corba.TStatusLevel(_LevelError);

  public int value ()
  {
    return __value;
  }

  public static edu.stanford.atom.sti.client.comm.corba.TStatusLevel from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TStatusLevel (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TStatusLevel
