package edu.stanford.atom.sti.client.comm.corba;

/**
* Timing_Server/TValMixedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/code/Timing_Server/timingserver.idl
* Tuesday, April 29, 2008 9:27:00 PM PDT
*/

public final class TValMixedHolder implements org.omg.CORBA.portable.Streamable
{
  public edu.stanford.atom.sti.client.comm.corba.TValMixed value = null;

  public TValMixedHolder ()
  {
  }

  public TValMixedHolder (edu.stanford.atom.sti.client.comm.corba.TValMixed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = edu.stanford.atom.sti.client.comm.corba.TValMixedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
        edu.stanford.atom.sti.client.comm.corba.TValMixedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return edu.stanford.atom.sti.client.comm.corba.TValMixedHelper.type ();
  }

}
