package edu.stanford.atom.sti.client.comm.corba;


/**
* Timing_Server/TVarMixed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/code/Timing_Server/timingserver.idl
* Tuesday, April 29, 2008 9:27:00 PM PDT
*/

public final class TVarMixed implements org.omg.CORBA.portable.IDLEntity
{
  private double ___number;
  private String ___stringVal;
  private short ___channel;
  private String ___objectVal;
  private edu.stanford.atom.sti.client.comm.corba.TType __discriminator;
  private boolean __uninitialized = true;

  public TVarMixed ()
  {
  }

  public edu.stanford.atom.sti.client.comm.corba.TType discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public double number ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifynumber (__discriminator);
    return ___number;
  }

  public void number (double value)
  {
    __discriminator = edu.stanford.atom.sti.client.comm.corba.TType.TypeNumber;
    ___number = value;
    __uninitialized = false;
  }

  public void number (edu.stanford.atom.sti.client.comm.corba.TType discriminator, double value)
  {
    verifynumber (discriminator);
    __discriminator = discriminator;
    ___number = value;
    __uninitialized = false;
  }

  private void verifynumber (edu.stanford.atom.sti.client.comm.corba.TType discriminator)
  {
    if (discriminator != edu.stanford.atom.sti.client.comm.corba.TType.TypeNumber)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public String stringVal ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifystringVal (__discriminator);
    return ___stringVal;
  }

  public void stringVal (String value)
  {
    __discriminator = edu.stanford.atom.sti.client.comm.corba.TType.TypeString;
    ___stringVal = value;
    __uninitialized = false;
  }

  public void stringVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator, String value)
  {
    verifystringVal (discriminator);
    __discriminator = discriminator;
    ___stringVal = value;
    __uninitialized = false;
  }

  private void verifystringVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator)
  {
    if (discriminator != edu.stanford.atom.sti.client.comm.corba.TType.TypeString)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public short channel ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifychannel (__discriminator);
    return ___channel;
  }

  public void channel (short value)
  {
    __discriminator = edu.stanford.atom.sti.client.comm.corba.TType.TypeChannel;
    ___channel = value;
    __uninitialized = false;
  }

  public void channel (edu.stanford.atom.sti.client.comm.corba.TType discriminator, short value)
  {
    verifychannel (discriminator);
    __discriminator = discriminator;
    ___channel = value;
    __uninitialized = false;
  }

  private void verifychannel (edu.stanford.atom.sti.client.comm.corba.TType discriminator)
  {
    if (discriminator != edu.stanford.atom.sti.client.comm.corba.TType.TypeChannel)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public String objectVal ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyobjectVal (__discriminator);
    return ___objectVal;
  }

  public void objectVal (String value)
  {
    __discriminator = edu.stanford.atom.sti.client.comm.corba.TType.TypeObject;
    ___objectVal = value;
    __uninitialized = false;
  }

  public void objectVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator, String value)
  {
    verifyobjectVal (discriminator);
    __discriminator = discriminator;
    ___objectVal = value;
    __uninitialized = false;
  }

  private void verifyobjectVal (edu.stanford.atom.sti.client.comm.corba.TType discriminator)
  {
    if (discriminator != edu.stanford.atom.sti.client.comm.corba.TType.TypeObject)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class TVarMixed
