package edu.stanford.atom.sti.client.comm.corba;


/**
* Timing_Server/TVariable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/code/Timing_Server/timingserver.idl
* Tuesday, April 29, 2008 9:27:00 PM PDT
*/

public final class TVariable implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public edu.stanford.atom.sti.client.comm.corba.TVarMixed value = null;
  public edu.stanford.atom.sti.client.comm.corba.TPosition pos = null;

  public TVariable ()
  {
  } // ctor

  public TVariable (String _name, edu.stanford.atom.sti.client.comm.corba.TVarMixed _value, edu.stanford.atom.sti.client.comm.corba.TPosition _pos)
  {
    name = _name;
    value = _value;
    pos = _pos;
  } // ctor

} // class TVariable
