/*! \file
 *  \author Jonathan David Harvey
 *  \author Jason Michael Hogan
 *  \author David Marvin Slaughter Johnson
 *  \author Olaf Mandel
 *  \brief Interface Definition of the Server-Device CORBA communication.
 *  \section license License
 *
 *  Copyright (C) 2008 Jonathan Harvey <harv@stanford.edu>\n
 *  Copyright (C) 2008 Jason Hogan <hogan@stanford.edu>\n
 *  Copyright (C) 2008 David Johnson <dmsj@stanford.edu>\n
 *  Copyright (C) 2008 Olaf Mandel <mandel@stanford.edu>\n
 *  This file is part of Stanford Timing Interface (STI).
 *
 *  STI is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  STI is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with STI.  If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef DEVICE_IDL
#define DEVICE_IDL

#include "orbTypes.idl"

module STI
{

module Server_Device
{

	//servant runs on the device
	interface DataLogger
	{
		STI::Types::TNetworkFileSeq getLogFiles();
		void clearLocalLogFiles();
	};


    // DeviceServer and Device object.
    interface Configure
    {
        // Configurable attributes presented by this device to the server
        readonly attribute STI::Types::TAttributeSeq attributes;
        readonly attribute string deviceName;

        boolean setAttribute(in string key, in string value);
        string getAttribute(in string key);

		void reRegisterWithServer();

		void kill();

//		string getCorbaError(in string timestamp);	//returns all CORBA error messages since timestamp

		// 11/07/2008 07:54 -- CORBA Error: ...
		// timestamp is generated on device to ensure a match
		// if timestamp is "" then it returns all errors
    };



    // Device object.
    //Create two instances of this:
    // * Continuously running elements
    // * Timing critical measurements
    interface DataTransfer
    {
        readonly attribute string             errMsg;	// device specific parsing errors?
//        readonly attribute TMeasurementSeqSeq measurements;
        readonly attribute STI::Types::TMeasurementSeq measurements;	//all the measurements

        STI::Types::TMeasurementSeq getStreamingData(in unsigned short channel,
                                         in double         initial_t, 
                                         in double         final_t, 
                                         in double         delta_t);

		STI::Types::TLabeledData getData(in string dataLabel);
    };

	// DeviceServer object.
    interface DeviceControl
    {
        readonly attribute string controlMsg;
        STI::Types::TStatus status();

        boolean transferEvents(in STI::Types::TDeviceEventSeq events, in boolean dryrun);
		readonly attribute string transferErr;
		readonly attribute boolean eventsParsed;
		readonly attribute boolean eventsLoaded;
		readonly attribute boolean eventsPlayed;

        void reset();
		void load();		//load events onto FPGA memory; non-FPGA devices do nothing
		boolean prepareToPlay();
        void play();        //Begin playback of stored events
		void pause();
//        void trigger();     //Manually trigger playback
        void stop();        //Stop current playback

		boolean ping();		//server can use to measure network transit time to this device
    };


    
    // Server object.  Devices establish contact with this (global) object and configure
    // the server for communication prior to making their servants live with orb->run()
    interface ServerConfigure
    {
        // The attributes required by the server for communication
        readonly attribute STI::Types::TAttributeSeq attributes;        
        readonly attribute string serverName;    //human-readable server id info

        // Returns true if registration is successful.
        // Asigns a unique TDevice.deviceID for the device.
        // The device uses the deviceID string to specify its attributes to the server.
        // The TDevice.deviceContext is used to register the device with the NameService.
        // This function (in particular, deviceID generation) MUST be thread safe!
        boolean registerDevice(inout STI::Types::TDevice device);

//        // Let's devices modify attributes for other devices on the server
  //      boolean setAttribute(in string deviceID, in string key, in string value);
    //    string getAttribute(in string deviceID, in string key);

        // Let's a device tell the server what channels it has available
        boolean setChannels(in string deviceID, in STI::Types::TDeviceChannelSeq channels);

        // Tells the server to aquire the device's servants in the unique context .\<deviceID>\
        // The device's servants should be live and available on the NameService before making this call.
        // Since orb->run() must be called from the main thread, the acquisition of the server's
        // ServerConfigure object and the call to activateDevice() should be done from
        // a separate (low priority) thread.
        boolean activateDevice(in string deviceID);
        boolean removeDevice(in string deviceID);

		//used to generate deviceIDs for partner devices
		string generateDeviceID(in STI::Types::TDevice device);

		void reportMessage(in string deviceID, in STI::Types::TMessageType type, in string message);

		void pauseServer(in string deviceID);
		void unpauseServer(in string deviceID);
    };


	//interface StatusMonitor	//lives on server
	//{
	//	void reportMessage(in string deviceID, in TMessageType, in string message);
	//};

	interface CommandLine;

	//should be renamed Partners
	interface CommandLine
	{
		readonly attribute STI::Types::TStringSeq eventPartnerDevices; //the partners that this device generates event for
		readonly attribute STI::Types::TStringSeq requiredPartnerDevices;
		readonly attribute STI::Types::TStringSeq registeredPartnerDevices;
//		readonly attribute string deviceID;
		readonly attribute STI::Types::TDevice device;

		//executing command line args on partner devices
		string execute(in string args);
        
		//allows devices to set attributes on partner devices
		boolean setAttribute(in string key, in string value);
        string getAttribute(in string key);

		boolean registerPartnerDevice(in CommandLine partnerCmdLine);
		boolean unregisterPartnerDevice(in string deviceID);

		STI::Types::TPartnerDeviceEventSeq getPartnerEvents(in string deviceID);

//		boolean transferPartnerEvents(in STI::Types::TDeviceEventSeq events);

	};

};

};

#endif

