#ifndef FILESERVER_IDL
#define FILESERVER_IDL

module Remote_File_Server
{
    struct TFile {
        string filename;
		boolean exists;
		boolean isDirectory;
		boolean isHidden;
		unsigned long lastModified;
		unsigned long length;
    };

	typedef sequence<TFile> TFileSeq;


    interface FileServer
    {
        readonly attribute string homeDirectory;

		boolean exists(in string file);
		boolean isFile(in string file);
		boolean isDirectory(in string file);
		boolean isAbsolute(in string path);

		boolean createNewFolder(in string containingDir, in string filename);

		TFileSeq getFiles(in string dir);
		TFile getParentFile(in TFile child);

		string normalize(in string path);
		string canonicalize(in string path);

		string getSeparator();
		string getAbsolutePath(in string path);
		long long getFileLength(in string path);
		long long getLastWriteTime(in string path);

		boolean isReadOnly(in string path);
		string readData(in string path);
		boolean writeData(in string path, in string data);
    };

};

#endif